### ISSUE TITLE
Question about the downloading project function

### ISSUE THREAD

**Issue by Chiroyce1** [TimMcCool/scratchattach#1]
> https://github.com/TimMcCool/scratch3.py/blob/c01b80b8bd2eb900d7aa40b0d5f28a066b92c396/scratch3/_project.py#L39

When downloading a project from `projects.scratch.mit.edu`, it only returns the project's JSON file ([example](https://projects.scratch.mit.edu/582160510/)), and SB3 files are actually a zipped up version of all the assets and the JSON file, but when writing only the JSON content to the SB3 file, I'm not sure if it would be a valid. When I tried it out with the online editor it worked successfully since the assets are already stored on the server, I'm not sure if it will be valid when you try to load it with the offline editor though.

**Comment by SpyC0der77** [comment]
no way chiroyce
