### ISSUE TITLE
Chrome Dev changed how to find cookies - Where are they?

### ISSUE THREAD

**Issue by CodeSoftGitHub** [TimMcCool/scratchattach#100]
This is an issue because in July this release comes out! The method of finding cookies is now different, and I have no idea where they are or how to find them.

**Comment by CodeSoftGitHub** [comment]
> Does the method [described on this page](https://github.com/TimMcCool/scratchattach/wiki/Get-your-session-id) still work in the new release?

The first method luckily still works, but the second method doesn't.

**Comment by programORdie2** [comment]
You also can use the CookieEditor chrome extension for getting your cookies.

**Comment by TimMcCool** [comment]
> > Does the method [described on this page](https://github.com/TimMcCool/scratchattach/wiki/Get-your-session-id) still work in the new release?
> 
> The first method luckily still works, but the second method doesn't.

Okay, then use the first method.
