### ISSUE TITLE
Frontpage functions don't work

### ISSUE THREAD

**Issue by RC9910-Scratch** [TimMcCool/scratchattach#106]
I'm trying to get the front-page projects, but doing so gives me this (example with featured projects:)

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    aList = scratch3.featured_projects()
  File "/home/runner/Scratch-Homepage/venv/lib/python3.10/site-packages/scratchattach/_session.py", line 363, in featured_projects
    return requests.get("https://api.scratch.mit.edu/proxy/featured").json()["community_featured_projects"]
KeyError: 'community_featured_projects'
```

Code:
```
import os

os.system("pip install -U scratchattach")

import scratchattach as scratch3

aList = scratch3.featured_projects()
print(aList)
```

I'm using replit to do this

**Comment by programORdie2** [comment]
Oh, logiq; replit has scratch blocked his IP. I would try to use a proxy and do the requests manually. (with requests, not scratchattach)

**Comment by TimMcCool** [comment]
Yes, replit blocked scratch from its API. You could try using a proxy or using an alternative to replit (like codesandbox.io or aws)
