### ISSUE TITLE
[INFO] Uploading projects

### ISSUE THREAD

**Issue by programORdie2** [TimMcCool/scratchattach#107]
Is it possible to load a .sb3 file to an existing project?

**Comment by mas6y6** [comment]
Idk

**Comment by TimMcCool** [comment]
That's not a scratchattach feature at the moment, but will maybe be added in the future

**Comment by programORdie2** [comment]
But so ScratchApi does have an endpoint for it?

**Comment by TimMcCool** [comment]
Yes. A method for uploading projects will be added soon :)

**Comment by programORdie2** [comment]
Can you say wich url, and wich headers?

**Comment by TheCommCraft** [comment]
It's just unzipping the .sb3, posting the project.json file to projects.scratch.mit.edu/<id> and uploading all the other assets

**Comment by programORdie2** [comment]
Can you be a little more specific?

**Comment by TheCommCraft** [comment]
I think that these things are implemented in the library scratchclient

programORdie2 ***@***.***> schrieb am So., 16. Juli 2023,
13:31:

**Comment by programORdie2** [comment]
Ok, i'll check

**Comment by programORdie2** [comment]
Nope

**Comment by TheCommCraft** [comment]
scratchclient.Project.Project.save()
scratchclient.ScratchSession.ScratchSession.upload_asset()

programORdie2 ***@***.***> schrieb am So., 16. Juli 2023,
14:52:

**Comment by TimMcCool** [comment]
project.set_json(json_data) was added in v1.4.5. A method for uploading assets will be added soon

**Comment by programORdie2** [comment]
Thanks!

**Comment by TimMcCool** [comment]
A method for uploading assets won't be added
