### ISSUE TITLE
user.follower_count doesn't work

### ISSUE THREAD

**Issue by Ellirio** [TimMcCool/scratchattach#108]
Idk if its working or not I did user.follower_count and it gave <bound method User.follower_count of <scratchattach._user.User object at 0x7feb6dc1ff70>> any ideas what it is :)

**Comment by programORdie2** [comment]
Maybe you should try: `user.follower_count()`

**Comment by TimMcCool** [comment]
yes, you have to do user.follower_count()

**Comment by Ellirio** [comment]
oh lol sorry i meant i typed user.follower_count() and it gave that error.

**Comment by programORdie2** [comment]
Can you please give your code and the full error?
