### ISSUE TITLE
Server receiving requests multiple times

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#109]
Copy of #84 because I can't find a way to reopen it. The problem still persists.

**Comment by programORdie2** [comment]
I also still have the problem, and it seems to be getting worse.

**Comment by TimMcCool** [comment]
Okay, I'll look into it again

**Comment by programORdie2** [comment]
Thanks

**Comment by Ellirio** [comment]
Same here

**Comment by programORdie2** [comment]
Maybe you could add the timestamp in the scratchrequest and controll of the timestamp of receiving is +- the same

**Comment by programORdie2** [comment]
Wait.Do `data_from_websocket=False` fixes it?

**Comment by TheCommCraft** [comment]
Yes, but it also takes more processing power and egress

programORdie2 ***@***.***> schrieb am So., 23. Juli 2023,
21:51:

**Comment by programORdie2** [comment]
oh :(

**Comment by mas6y6** [comment]
I am having the issue and its glitches my scratchattach project

**Comment by programORdie2** [comment]
Yeah, i'm making a AI image generator, but it takes lot CPU power to gnerate a image, so it's anoying if you need to create a image for a ghost.

**Comment by TheCommCraft** [comment]
@TimMcCool Will you?

**Comment by TimMcCool** [comment]
I will try to find a solution, yes

**Comment by programORdie2** [comment]
@TimMcCool  TYSM!

**Comment by TimMcCool** [comment]
The issue should be fixed. If it happens again, please give me a link to the project where it happened and the scratchattach version used

**Comment by programORdie2** [comment]
Scratchattach v1.3.0, link: https://scratch.mit.edu/projects/880182491/

**Comment by programORdie2** [comment]
@TimMcCool Can you fix it?

**Comment by TimMcCool** [comment]
Merged into #130
