### ISSUE TITLE
I Am Using Replit How To Setup Proxy

### ISSUE THREAD

**Issue by AzimuthPulse** [TimMcCool/scratchattach#110]
As Scratch Banned Replit How To Set Up Proxy
code:
import scratchattach as scratch3
import requests
import json
import os
import keep_alive
from threading import Thread

SECRET = os.environ['session_id']

session = scratch3.Session(SECRET, username="005742")
conn = session.connect_cloud("874882103")

client = scratch3.CloudRequests(conn)

def Get_Check(user, username):
  user = user = session.connect_user(user)
  return user.is_followed_by(username)
@client.request
def Check(use, usernam):
  print("request received")
  try:
    return Get_Check(use, usernam)
  except:
    return "Error, try again in 5 mn"

@client.event
def on_ready():
  print("Request handler is running")

Thread(target=keep_alive.keep_alive).start()
client.run()

**Comment by programORdie2** [comment]
You should do: `response = requests.get(proxy_url + 'https://api.scratch.mit.edu/somet/thing.json()`

**Comment by shamil-pallath** [comment]
thnX

**Comment by shamil-pallath** [comment]
but can you edit the code and give me I am new to this I don't know much about proxy

**Comment by programORdie2** [comment]
ok

**Comment by programORdie2** [comment]
Uhm, the code you wrote doesn't use the scratchapi, so you don't need a proxy

**Comment by NotFenixio** [comment]
Note: using proxies in Replit is against their ToS, and will get your project disabled for some time.

**Comment by programORdie2** [comment]
> 

Really?

**Comment by NotFenixio** [comment]
https://replit.com/site/terms#:~:text=Use%20the%20Service%20to%20create%20a%20proxy%20with%20the%20purpose%20of%20circumventing%20any%20firewall%20or%20other%20access%20control%20measure%3B
I mean, they say creating a proxy, but one of my projects got blocked because I was using a proxy to access the Scratch API.

**Comment by programORdie2** [comment]
I use a proxy in almost every project i make, and None of them got ever blocked ...

**Comment by AzimuthPulse** [comment]
i started using github workflows as an alternative I will close this issue
