### ISSUE TITLE
scratchattach._project.Project object at 0x0000016F34008F40

### ISSUE THREAD

**Issue by Ankpudding** [TimMcCool/scratchattach#114]
I get this when i try to fetch all my projects do anyone know how to fix this

**Comment by programORdie2** [comment]
Whats your code?

**Comment by mas6y6** [comment]
Umm thats a class object

**Comment by mas6y6** [comment]
scratchattach creates a `Project` class object for each project so it can be easier to get the project info for example

if you are searching for projects using 
```python
import scratchattach as scratch3

result = scratch3.search_projects(query="query", mode="trending", language="en", limit=40, offset=0)
```
you will get a list back looking like this
```python
[<scratchattach._project.Project object at 0x1061656d0>, <scratchattach._project.Project object at 0x106794510>, <scratchattach._project.Project object at 0x106794610>, <scratchattach._project.Project object at 0x1067947d0>, etc....
```
to get the info from the list use this
```python
result[0].<Functions or variables>
```
All of the Functions can be found [here](https://github.com/TimMcCool/scratchattach#projects)

**Comment by mas6y6** [comment]
I hope that helps 😄

**Comment by TimMcCool** [comment]
The attributes and method of the scratchattach._project.Project class are documented here: https://github.com/TimMcCool/scratchattach#projects

**Comment by mas6y6** [comment]
Hey tim this issue needs to be labeled as "Support"

**Comment by TimMcCool** [comment]
This repo currently doesn't have a support label, I'll create one

Anyways I'll close this issue because of inactivity

**Comment by Ankpudding** [comment]
Thank you so much for helping me
