### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by RC9910-Scratch** [TimMcCool/scratchattach#115]
1) Is it possible to get the curated projects (and the current curator)?
2) Can I connect to the scratch cloud and the turbowarp cloud with the same script?

**Comment by TheCommCraft** [comment]
2: Yes, if you use CloudRequests, you can use CloudRequests.start(thread=True) to use threads

**Comment by programORdie2** [comment]
2. No, i don't think, cuz you then need to redefine a function.

**Comment by TheCommCraft** [comment]
> 2. No, i don't think, cuz you then need to redefine a function.

I think they meant in the same program not in the same function

**Comment by programORdie2** [comment]
But you need the same function name, else you don't get the right request?

**Comment by TheCommCraft** [comment]
Well yeah, but you can reuse the name of the function in this case because
the scratchattach._cloud_requests.CloudRequests.request method returns None
and not a function. Even if, you could use
scratchattach._cloud_requests.CloudRequests.request(name="yourrequesrname")
and just call the function something else

programORdie2 ***@***.***> schrieb am Do., 27. Juli 2023,
09:10:

**Comment by RC9910-Scratch** [comment]
I think it's possible to create another function for turbowarp with the 'is compiled?' block in scratch

**Comment by TheCommCraft** [comment]
Yes, but it isn't necessary

RC9910-Scratch ***@***.***> schrieb am Do., 27. Juli 2023,
14:28:

**Comment by TimMcCool** [comment]
1. Yes, you can use
```
curated_projects = scratch3.curated_projects()
curator = curated_projects[0]["curator_name"]
```
2. Yes, you can do something like this:
```py
import scratchattach as scratch3

session = scratch3.Session("session_id", username="username") #replace with your session_id and username
conn_scratch = session.connect_cloud("project_id") #replace with your project id
client_scratch = scratch3.CloudRequests(conn_scratch )

conn_tw = scratch3.TwCloudConnection(project_id="project_id") #replace with your project id
client_tw = scratch3.TwCloudRequests(conn_tw )

def example_request(arg1):
    return "pong"

client_scratch.add_request(example_request)
client_tw.add_request(example_request)

client_scratch.run(thread=True)
client_tw.run()
```

**Comment by RC9910-Scratch** [comment]
thx :)
