### ISSUE TITLE
Secure data transmition

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#116]
Will there be secure data transmition in CloudRequests so that only the right server can read messages and respond to them?

**Comment by mas6y6** [comment]
idk

**Comment by TheCommCraft** [comment]
The question wasn't directed at you

mas6y6 ***@***.***> schrieb am Do., 27. Juli 2023, 04:21:

**Comment by programORdie2** [comment]
The problem is that they take a lot of time to send data securely.

**Comment by TheCommCraft** [comment]
Yeah, but on turbowarp that isn't really a problem

programORdie2 ***@***.***> schrieb am Do., 27. Juli 2023,
08:59:

**Comment by programORdie2** [comment]
But 85% of the people uses scratch

**Comment by TheCommCraft** [comment]
Yeah but on Scratch, nobody can just impersonate you, on turbowarp anyone
can do it right now.

programORdie2 ***@***.***> schrieb am Do., 27. Juli 2023,
09:03:

**Comment by programORdie2** [comment]
Thats true

**Comment by TimMcCool** [comment]
This feature won't be added to scratchattach
