### ISSUE TITLE
Wrong values in the cloud events

### ISSUE THREAD

**Issue by ejnalo** [TimMcCool/scratchattach#118]
Hey, I was working w/ the cloud variables but scratchattach returns me values that either were not set for minutes or don't even appear in my Cloud Monitor (ignore the "Changed" lines):
![ps](https://github.com/TimMcCool/scratchattach/assets/110610727/5a5de46a-69e5-49c4-946a-9e95e3e60b86)
![cm](https://github.com/TimMcCool/scratchattach/assets/110610727/5e1e943e-e0c6-4f6c-af74-36a27052b546)

**Comment by TimMcCool** [comment]
What cloud events were you using? (scratch3.CloudEvents or scratch3.WsCloudEvents)

**Comment by TimMcCool** [comment]
scratchattach's cloud events receive data from the clouddata API. According to Scratch's clouddata API, the variable Request was set to the values 101112131415, 1119 and 14: https://clouddata.scratch.mit.edu/logs?projectid=877118077&limit=30&offset=0

**Comment by TimMcCool** [comment]
Are you sure the project id in your code is correct? The clouddata API should not differ from the cloudmonitor
