### ISSUE TITLE
help

### ISSUE THREAD

**Issue by usernamebroken** [TimMcCool/scratchattach#119]
![Screenshot 2023-07-27 132600](https://github.com/TimMcCool/scratchattach/assets/129422252/662a09de-7234-4a55-b300-d97d890a485c)

**Comment by programORdie2** [comment]
You just showed your password :/

**Comment by usernamebroken** [comment]
i know :(

**Comment by RC9910-Scratch** [comment]
You can edit the original message and delete the picture showing your password, else there is a chance of being hacked

**Comment by programORdie2** [comment]
And I would change your password as well.

**Comment by usernamebroken** [comment]
i did
