### ISSUE TITLE
[QUESTION] Are you going to make a logo for scratchattach?

### ISSUE THREAD

**Issue by mas6y6** [TimMcCool/scratchattach#121]
Are you going to make a logo for scratchattach?

**Comment by programORdie2** [comment]
if you have to uch time, you always can make a tutorial how to use scratchrequest (my library) :D

**Comment by mas6y6** [comment]
UMm

**Comment by mas6y6** [comment]
Idk I would rather make a tutorial for scratchattach because a lot of people are having a hard time using scratchattach

**Comment by TimMcCool** [comment]
> Are you going to make a logo for scratchattach?

maybe

> Because I am going to make a tutorial of how to use scratchattach

sounds interesting, I'm sure it will help people who are new to python

**Comment by mas6y6** [comment]
Ok and thx

**Comment by mas6y6** [comment]
I am bad at logo design but I am going to try tho

**Comment by programORdie2** [comment]
@mas6y6 FelixCodeur (on scratch) made one. Idk if it's still shared, but maybe you can use that.

**Comment by Sussy-OS** [comment]
I'll try making a logo too. I have a neat idea that I think you might like.

**Comment by programORdie2** [comment]
> I'll try making a logo too. I have a neat idea that I think you might like.

Can you send my a message or comment on my scratch if it's done or say me where i can find it when it's done?

**Comment by Sussy-OS** [comment]
> > I'll try making a logo too. I have a neat idea that I think you might like.
> 
> Can you send my a message or comment on my scratch if it's done or say me where i can find it when it's done?

When it's done, I'll send the svg file here. I recommend using boxy svg to export the image to whatever size you need. It _is_ a payed program, but I like it a lot, and on linux it's free. (Don't use scratch to export an image of it, please use an actual svg program.)

**Comment by TimMcCool** [comment]
This will be the scratchattach logo for now:

![image](https://github.com/TimMcCool/scratchattach/assets/53166177/e4f48166-7d18-45d4-947a-77514798f7fb)

If you have ideas for a better logo, feel free to post them here :)

**Comment by Sussy-OS** [comment]
> This will be the scratchattach logo for now:
> 
> ![image](https://user-images.githubusercontent.com/53166177/263552487-e4f48166-7d18-45d4-947a-77514798f7fb.png)
> 
> If you have ideas for a better logo, feel free to post them here :)

Alright. That's actually literally what I was doing, but you did it _way_ better.

**Comment by programORdie2** [comment]
Maybe you can add something scratchy?

**Comment by NotFenixio** [comment]
> Maybe you can add something scratchy?

Like this?
![image](https://github.com/TimMcCool/scratchattach/assets/103071021/c00050ca-57f7-4580-a242-3abbae58d336)

**Comment by programORdie2** [comment]
Awesome!!!
