### ISSUE TITLE
[QUESTION] Will you ever share example programs?

### ISSUE THREAD

**Issue by Sussy-OS** [TimMcCool/scratchattach#122]
Will you ever show example programs like your pfp and stats lookup? I would love to see how they work, so I could make something of my own!

**Comment by Sussy-OS** [comment]
> Do you mean Python or Scratch3 Examples???

Python, because the Scratch code is already on the public project.

**Comment by Sussy-OS** [comment]
The scratch code for receiving the data (not displaying it) seems very simple, so I'm assuming the python code does most of the work.

**Comment by programORdie2** [comment]
You can find exaples on replit, becouse most of the people use that site to host

**Comment by TimMcCool** [comment]
clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though

**Comment by Sussy-OS** [comment]
> clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though

Alright, thanks! What is this though? https://replit.com/@1Tim?showcase=1&tab=repls#scratchsocket.py

**Comment by Sussy-OS** [comment]
I think it would be helpful for a few people though, to just make generic example programs, that do simple things, and put them in like an `examples` directory.

**Comment by Sussy-OS** [comment]
> clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though

What _did_ you use for those projects then?

**Comment by TimMcCool** [comment]
> > clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though
> 
> What _did_ you use for those projects then?

websocket-client and requests (these libraries are used by scratchattach too)

**Comment by TimMcCool** [comment]
> > clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though
> 
> Alright, thanks! What is this though? https://replit.com/@1Tim?showcase=1&tab=repls#scratchsocket.py

What repl are you talking about? scratchsocket is a library by another Scratcher. It is similar to scratchattach, but has less features

**Comment by Sussy-OS** [comment]
> > > clooud blocky, pfp lookup and stats lookup were not made with scratchattach (I made these projects before I made scratchattach). But the infinite leaderboard of (this game)[https://scratch.mit.edu/projects/404659699/] was made with scratchattach, and it's open source. Backend code: https://replit.com/@1Tim/Ice-Cube-Smash-LB#main.py I'm not sure if it's going to help you though
> > 
> > 
> > Alright, thanks! What is this though? https://replit.com/@1Tim?showcase=1&tab=repls#scratchsocket.py
> 
> What repl are you talking about? scratchsocket is a library by another Scratcher. It is similar to scratchattach, but has less features

Oh, sorry I was talking about scratch stats: https://replit.com/@1Tim/ScratchStatsI1

**Comment by Sussy-OS** [comment]
quick side question: how do you deal with two requests at the same time?

**Comment by TimMcCool** [comment]
I shared some example scripts: https://github.com/TimMcCool/scratchattach/wiki/Examples Example projects are coming soon
