### ISSUE TITLE
i try to make my own acc heart someone elses project but project.love() doesnt work

### ISSUE THREAD

**Issue by gamecraft213** [TimMcCool/scratchattach#124]
my code:
import scratchattach as scratch3
import os
import time
os.system("pip install -U scratchattach")

session = scratch3.login("BADPlGGlE", "*********")
projectID = 8765547912
apple = 1

while apple < 20:
    projectConnect = session.connect_project(projectID)  # connects to the project
    projectID = projectID + 1
    apple = apple + 1
    projectConnect.love()  # Returns the author as scratch3.User object
    time.sleep(5)

the error:
[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/Users/******/PycharmProjects/pythonProject1/main.py", line 14, in <module>
    projectConnect.love()  # Returns the author as scratch3.User object
**AttributeError: 'PartialProject' object has no attribute 'love'**

**Comment by gamecraft213** [comment]
all ******** is blurred btw becuase it contains personal info and passwords

**Comment by gamecraft213** [comment]
actually all project.action() doesnt work, it gives the same error

**Comment by programORdie2** [comment]
Why do you increment the project ID?

**Comment by programORdie2** [comment]
Is it possible the project is unshared?

**Comment by TimMcCool** [comment]
That's because the project is unshared and not owned by the BADPlGGlE account

**Comment by gamecraft213** [comment]
but anything with project. doesnt work bc of the error

**Comment by gamecraft213** [comment]
but ill try

**Comment by TheCommCraft** [comment]
The first output is just a warning, not an error. The second error is because the scratch api prevents you from interacting with unshared project
