### ISSUE TITLE
Cloud Connection Error

### ISSUE THREAD

**Issue by programORdie2** [TimMcCool/scratchattach#125]
Sometimes, after my requesthandler is running for a while, i got the error scratchattach._exceptions.ConnectionError. I don't know the whole exception anymore, but it turned out that the variable timeout was not defined (here: https://github.com/TimMcCool/scratchattach/blob/b1ca0ce1f5ceb948ce900c9d0fcf7bc889835244/scratchattach/_cloud.py#L82C29-L82C36)

**Comment by RC9910-Scratch** [comment]
Is this the error you got?

`User is pinging the server
Warning: Caught error in request 'ping' - Full error below
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud.py", line 67, in _connect
    self.websocket.connect(
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway -+-+- {'date': 'Sun, 06 Aug 2023 18:49:47 GMT', 'content-type': 'text/html', 'content-length': '157', 'connection': 'keep-alive', 'server': 'nginx/1.22.1'} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud.py", line 82, in _connect
    timeout=timeout
            ^^^^^^^
NameError: name 'timeout' is not defined`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud_requests.py", line 107, in call_request
    self._parse_output(output, request, req_obj, request_id)
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud_requests.py", line 316, in _parse_output
    self._respond(request_id, output, self.packet_length)
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud_requests.py", line 197, in _respond
    self.connection._connect(cloud_host=self.connection.cloud_host)
  File "/usr/local/lib/python3.11/site-packages/scratchattach/_cloud.py", line 85, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError`

**Comment by programORdie2** [comment]
Yes, except it's not with a request called ping.

**Comment by AzimuthPulse** [comment]
its a bug with the cloud requests it will even run after showing that error I get this sometimes and I am actually 005742 I just changed my acc to AzimuthPulse so I also changed my username

**Comment by TimMcCool** [comment]
It looks like there's a bug in the current scratchattach version, cloudrequests are not handling websocket disconnects properly. Will be fixed soon

**Comment by TimMcCool** [comment]
The bug is fixed now. Update scratchattach with pip install -U scratchattach. Sorry for the inconvenience.

Please tell me if the update fixed the bug so I can close the topic

**Comment by programORdie2** [comment]
I didn't happen again in a few houres, so i think it's solved.
