### ISSUE TITLE
My project is receiving ghost requests

### ISSUE THREAD

**Issue by RC9910-Scratch** [TimMcCool/scratchattach#130]
Probably the same as #109 

My project keeps on receiving requests that I did not request, but they could be requests that were made before.
I am using replit.

**Comment by Sussy-OS** [comment]
It happens to me only when in the editor, when all my code is finished and am not in the editor, it works fine.

**Comment by programORdie2** [comment]
> Probably the same as #109
> 
> My project keeps on receiving requests that I did not request, but they could be requests that were made before. I am using replit.

It should be fixed, did you updated your version?

**Comment by RC9910-Scratch** [comment]
> > Probably the same as #109
> > My project keeps on receiving requests that I did not request, but they could be requests that were made before. I am using replit.
> 
> It should be fixed, did you updated your version?

My scratchattach version is at 1.3.2

**Comment by RC9910-Scratch** [comment]
![image](https://github.com/TimMcCool/scratchattach/assets/139270767/6cf3710b-0ab0-43b8-b9df-6b8993d6f0f2)
![image](https://github.com/TimMcCool/scratchattach/assets/139270767/fd12c623-e140-4c7c-a82e-38d907f7a814)

**Comment by Sussy-OS** [comment]
> ![image](https://user-images.githubusercontent.com/139270767/262462224-6cf3710b-0ab0-43b8-b9df-6b8993d6f0f2.png) ![image](https://user-images.githubusercontent.com/139270767/262462854-fd12c623-e140-4c7c-a82e-38d907f7a814.png)

it may or may not be because you are using replit

**Comment by Sussy-OS** [comment]
For me, it happens when I go to my stuff, and click see inside or when its saving.

**Comment by TimMcCool** [comment]
Yeah same as #109

**Comment by TimMcCool** [comment]
Will be fixed

**Comment by TimMcCool** [comment]
The bug is most likely fixed now (update scratchattach). If it still happens, then please send me a screenshot of the clouddata log and your python backend code

**Comment by RC9910-Scratch** [comment]
I don't think it's happening anymore, so I think its fixed

**Comment by RC9910-Scratch** [comment]
Might be because they were not responded to

**Comment by Sussy-OS** [comment]
> Might be because they were not responded to

Yeah, but it's still a ghost request

**Comment by RC9910-Scratch** [comment]
Did you update your scratchattach version?

**Comment by Sussy-OS** [comment]
> Did you update your scratchattach version?

Yep, it's on 1.3.7
