### ISSUE TITLE
Enrichment: Hey tim I am making a repo that have examples for scratchattach

### ISSUE THREAD

**Issue by mas6y6** [TimMcCool/scratchattach#131]
Hey tim I am making a repo that have examples for scratchattach

Its in the works I thought you may check it out

[Examples](https://github.com/mas6y6/scratchattach-examples)

**Comment by Sussy-OS** [comment]
Hopefully you like some of these examples, and possibly add them to the documentation.

**Comment by programORdie2** [comment]
I made a repl that how 11 of my SA projects. It was made to have less egress, but maybe you can use it?

**Comment by TimMcCool** [comment]
Cool! I'll maybe add this to the documentation

**Comment by programORdie2** [comment]
https://replit.com/@programORdie/SA-servers-or-Host-1, sorry for the weird name

**Comment by RC9910-Scratch** [comment]
> https://replit.com/@programORdie/SA-servers-or-Host-1, sorry for the weird name

nice!

**Comment by programORdie2** [comment]
Really?

**Comment by RC9910-Scratch** [comment]
yep!

**Comment by programORdie2** [comment]
oh, ok

**Comment by TimMcCool** [comment]
Are you still working on this? I linked it here: https://github.com/TimMcCool/scratchattach/wiki/Examples#example-projects

**Comment by mas6y6** [comment]
I dont have the time i need more people

**Comment by programORdie2** [comment]
try on this: https://github.com/programORdie2/servers24-7

**Comment by TimMcCool** [comment]
> try on this: https://github.com/programORdie2/servers24-7

Added a link to it to the wiki, thanks!
