### ISSUE TITLE
Add a method to stop running the cloudrequests

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#132]
Could you make a method that stops the execution of the cloudrequests

**Comment by TimMcCool** [comment]
ok, will be added in the next update

**Comment by programORdie2** [comment]
I think if you stop the cloud, the cloudrequest also stops.

**Comment by TimMcCool** [comment]
has been added. You can now use client.stop() to stop the request handler and all background event listeners. Please note that the request handler won't stop immediately, if it's currently running a request it will still repond to it
