### ISSUE TITLE
Can we add: to switch the servers of TurboWarp, submit a project.

### ISSUE THREAD

**Issue by Boubou78000** [TimMcCool/scratchattach#135]
Project.set_json(JSON: dict) => None

**Comment by Boubou78000** [comment]
Session.set_project(project: FileName, project_id: str| int) => None
Submits the project to Scratch servers.
project= " [...] .sb3" .

**Comment by TimMcCool** [comment]
A function to set the project json will maybe be added

**Comment by TimMcCool** [comment]
project.set_json(json_data) was added in v1.4.5. A method for uploading assets will be added soon
