### ISSUE TITLE
Is it possible to play a video using this?

### ISSUE THREAD

**Issue by Stoutscientist** [TimMcCool/scratchattach#136]
I was messing around with this and was wondering if it would be possible to play a video using this by converting the video to base64 or something like that with a decoder in scratch and get at least 1fps? Even if it has to buffer the video into a list or something like that.

**Comment by programORdie2** [comment]
With a resolution of 50x50, at a FPS of 1, 50 seconds video would take 16 minutes to transmit.

**Comment by Stoutscientist** [comment]
yikes

**Comment by programORdie2** [comment]
With a lowwer resolution, base64 encoding and pixel compressing, you can very maybe get 5 min.

**Comment by Stoutscientist** [comment]
I heard someone got a browser working years ago, do you know if that actually show'd the page or if it was just basic html text?

**Comment by RC9910-Scratch** [comment]
I think it only showed the basic html text.

**Comment by Stoutscientist** [comment]
That makes sense, I want to try to recreate it but only allow whitelisted sites/have content filtering.

**Comment by NotFenixio** [comment]
One of the issues with sending images to Scratch is that almost all of them are corrupted. I mean, they get randomly cut off or with a weird offset in some rows.

**Comment by Stoutscientist** [comment]
I really wish the ST would just implement an extension for this

**Comment by programORdie2** [comment]
Yeah

**Comment by TimMcCool** [comment]
In Scratch it's not possible, but in turbowarp it is

**Comment by NotFenixio** [comment]
Well, it is. You can send a 1 FPS video, like a slideshow.

**Comment by RC9910-Scratch** [comment]
> Well, it is. You can send a 1 FPS video, like a slideshow.

If it was a 1hr video, that would be 3600 frames (60 secs * 60 mins)
