### ISSUE TITLE
user.viewed_projects is broken for me

### ISSUE THREAD

**Issue by PPPDUD** [TimMcCool/scratchattach#138]
Whenever I log into my account and use user.viewed_projects(limit=24, offset=0), it gives me an "unauthorized" error.

Edit: Fixed typo.

**Comment by TimMcCool** [comment]
You can only use this function on yourself. You can't see other users' viewed projects

**Comment by TimMcCool** [comment]
Update: It appears there's actually a bug that prevents you from using this function. Will be fixed soon

**Comment by PPPDUD** [comment]
> Update: It appears there's actually a bug that prevents you from using this function. Will be fixed soon. It should work in all version older than 1.4.0

Oh, I see. Now I regret installing 1.4.7 on my machine.

**Comment by TimMcCool** [comment]
It should be fixed now (update to v1.4.8)
