### ISSUE TITLE
Enhancement: Add client.add_event() (+ typo error)

### ISSUE THREAD

**Issue by RC9910-Scratch** [TimMcCool/scratchattach#139]
`client.add_event(function, new_name='new_name')`
Adds an event to the cloudrequests
Would be useful with projects that connect with the scratch and tw cloudrequests

**Comment by TimMcCool** [comment]
You can already do this using `client.event(function)`. This will add an event to the cloud requests

**Comment by RC9910-Scratch** [comment]
Ok, also there's a typo in the 'Examples' tab of the wiki

Cloud event handler:

`import scratchattach as scratch3`
`events = scratch3.CloudEvents("project_id")`

`@events.event`
`def on_set(event): #Called when a cloud var is set`
`    print(f"{event.user} set the variable {event.var} to the _valuee_ **value** {event.value} at {event.timestamp}")`

`events.start()`

**Comment by TimMcCool** [comment]
Fixed the wiki typo. `client.add_event(function, new_name)` will maybe be added. For now use `client.event(function)`

**Comment by RC9910-Scratch** [comment]
ok, closing
