### ISSUE TITLE
Cloud varables

### ISSUE THREAD

**Issue by mas6y6** [TimMcCool/scratchattach#143]
There has been an ongoing issue with cloud variables lately on the scratch website and its affecting **All scratchattach servers** all over the world.

So if your SA server is not working, it could the cloud issue.

Updates will be posted

**Comment by mas6y6** [comment]
Update 10/9/23 logging down

<img width="988" alt="Screenshot 2023-10-09 at 5 13 23 PM" src="https://github.com/TimMcCool/scratchattach/assets/125225333/bcb2235d-2fdf-474a-8347-18803b27e75f">

**Comment by Sussy-OS** [comment]
> Update 10/9/23 logging down
> 
> <img alt="Screenshot 2023-10-09 at 5 13 23 PM" width="988" src="https://user-images.githubusercontent.com/125225333/273710408-bcb2235d-2fdf-474a-8347-18803b27e75f.png">

Logging has been an issue for a week or two as far as I know. Maybe the cloud variables as well!

**Comment by mas6y6** [comment]
The scratch cloud servers that SA runs on is down (REDIRECT ERROR)

<img width="694" alt="Screenshot 2023-10-10 at 6 53 11 AM" src="https://github.com/TimMcCool/scratchattach/assets/125225333/b6ac9773-bf5f-4812-82ec-cd7c6392babb">

**Comment by TimMcCool** [comment]
Yes, Scratch's cloud logs are currently broken. Last week I released an update so scratchattach's cloud requests do still work. If your scratchattach project stopped working when the cloud logs broke, I'd recommend updating

**Comment by TimMcCool** [comment]
#144
