### ISSUE TITLE
[IMPORTANT] Cloud Requests are currently not working due to a Scratch incident. Update scratchattach to resolve the issue

### ISSUE THREAD

**Issue by TimMcCool** [TimMcCool/scratchattach#144]
Scratch's cloud logs have been broken for about two weeks. This caused scratchattach's cloud requests to stop working. The Scratch team still hasn't fixed the problem, therefore I released an update so cloud requests will still work even when the cloud logs are down.

Run `pip install -U scratchattach` to install the update

**Comment by mas6y6** [comment]
Umm tim its not working

**Comment by okazu0208** [comment]
this is so good!!

**Comment by sm4rd4** [comment]
hmm, i believe this update stopped the "request.requester" function from working, as when i run it it just returns "None"
![image](https://github.com/TimMcCool/scratchattach/assets/124947403/f7a0e72f-9b53-4a08-84ea-3780e3ebb053)

**Comment by TimMcCool** [comment]
> hmm, i believe this update stopped the "request.requester" function from working, as when i run it it just returns "None" ![image](https://user-images.githubusercontent.com/124947403/275670146-f7a0e72f-9b53-4a08-84ea-3780e3ebb053.png)

Yep. Atm the client.get_requester() function isn't working because the cloud logs are down

**Comment by gamecraft312** [comment]
is this still a problem or not? in my scratch project the request status var keeps saying TIMEOUT . . .

**Comment by ziqiangao** [comment]
Cloud Logs are now back up

**Comment by TimMcCool** [comment]
cloud logs are working again
