### ISSUE TITLE
Workaround for session.get_linked_user (for SA coders)

### ISSUE THREAD

**Issue by crashbandicootsthe1** [TimMcCool/scratchattach#145]
```
@client.request
def connect_user(username):
  linked_user = username
  return linked_username
```

i think this is true (please add enhancement category)

**Comment by TimMcCool** [comment]
What is this supposed to do / be for?

**Comment by crashbandicootsthe1** [comment]
Maybe my workaround for rate limits (i use replit)

**Comment by DebugDungeon** [comment]
it doesnt work this way, it rather fetches the session id and stores it in the class

**Comment by TimMcCool** [comment]
This whole issue looks very invalid. I think you confused a lot of things tbh. As DebugDungeon said it doesn't work this way
