### ISSUE TITLE
scratchattach.get_var() is not working

### ISSUE THREAD

**Issue by UrbanSkeleton** [TimMcCool/scratchattach#147]
When I try to get a cloud variable using get_var(), it always returns 'None'. Have no idea why this is happening. However, set_var() works as expected.
<img width="730" alt="Screen Shot 2023-10-17 at 7 23 00 PM" src="https://github.com/TimMcCool/scratchattach/assets/97252619/f4466358-750c-4076-b265-6a6650e7f69a">

**Comment by programORdie2** [comment]
The same happens when you try to get requester, i think this is becouse the cloudlogs are down

**Comment by TimMcCool** [comment]
Yes, it's because Scratch's cloud logs are currently not working
