### ISSUE TITLE
Local projects and communication

### ISSUE THREAD

**Issue by replicatesyndicate** [TimMcCool/scratchattach#148]
Is it possible to run **local** projects in the Scratch [app](https://scratch.mit.edu/download), without User/Password information or a `sessionId`?
I'm working with external hardware, and communication to it will be through a Python script that mustn't be tampered with, and preferably takes no inputs. It is also okay if the Scratch project receives *nothing* from the Python script, i.e. I just want to read some variables from Scratch.  

**From PyPI:**
Get a Scratch cloud var from the clouddata logs:  
Does not require a connection / session.  
```
value = scratch3.get_var("project_id", "variable")
variables = scratch3.get_cloud("project_id") #Returns a dict with all cloud var values
```
Is `project_id` in this case something that is reached online, or could a **local** project be accessed with its own ID number?  
Would such an ID number be constant? 
Is it possible to sniff current `project_ID` values of Scratch projects running on the machine?  

Finally, is it possible to run the following line with something like `localhost` instead?
```
conn = scratch3.TwCloudConnection(project_id = "project_id", username="username", cloud_host="<wss://clouddata.turbowarp.org")
```

**Comment by Ongenix** [comment]
You could convert your project to Javascript using [Turbowarp](turbowarp.org) and run them locally, then somehow grab variable data from the project (using Javascript or Python's selenium package) and input it into Scratchattach. My approach is a bit far fetched, but could theoretically work.

**Comment by TimMcCool** [comment]
```py
value = scratch3.get_var("project_id", "variable")
variables = scratch3.get_cloud("project_id") #Returns a dict with all cloud var values
```
These functions will send / get data from Scratch's cloud variable server.
> Is project_id in this case something that is reached online
Yes. It's the id that the project has on the Scratch website (scratch.mit.edu/projects/**project_id**/)
> or could a local project be accessed with its own ID number
No, and cloud variables don't work on local projects anyways, the only work on projects posted on the Scratch website.

> Finally, is it possible to run the following line with something like localhost instead?
> 
> conn = scratch3.TwCloudConnection(project_id = "project_id", username="username", cloud_host="wss://clouddata.turbowarp.org")
Yes, it's technically possible (if you manage it to host a websocket server on your computer and then open the project on turbowarp with the  URL of the locally hosted websocket as cloud host: https://docs.turbowarp.org/url-parameters#cloud_host)
