### ISSUE TITLE
Error while using post_comment

### ISSUE THREAD

**Issue by DebugDungeon** [TimMcCool/scratchattach#149]
getting error: 
```
Traceback (most recent call last):
  File "c:\Users\SHAMIL\OneDrive\Desktop\import scratchattach as scratch3.py", line 10, in <module>
    project.post_comment(content="...", commentee_id=122259700)
  File "C:\Users\SHAMIL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scratchattach\project.py", line 537, in post_comment
    raise(exceptions.Unauthenticated)
scratchattach.exceptions.Unauthenticated: You can't perform this action because you're not logged in. The object on which the method was called wasn't created with a session. More information: https://scratchattach.readthedocs.io/en/latest/scratchattach.html#scratchattach.exceptions.Unauthenticated 
```
while using post_comment
my code:
```
import scratchattach as scratch3
session = scratch3.Session(username="DebugDungeon", session_id=os.environ["session_id"])
user = scratch3.get_user("DebugDungeon")
project = scratch3.get_project(907085556)
project.post_comment(content="...", commentee_id=122259700)
```

**Comment by DebugDungeon** [comment]
> You need to login with password to make it work.

i did use password first then i changed to session id both doesnt work

**Comment by programORdie2** [comment]
You should use connect_project (or something similar), instead of get_project

**Comment by programORdie2** [comment]
run this code:
`import scratchattach as scratch3
session = scratch3.login(username="DebugDungeon", password=os.environ["password"])
project = session.connect_project("project_id")
project.post_comment(content="...", commentee_id=122259700)`

**Comment by RC9910-Scratch** [comment]
1. use `session.connect_project('project_id') to connect to projects rather than `scratch3.get_project('project_id')
2. `project.post_comment` doesn't need a commentee id, it only needs `content` (`project.post_comment(content='...')`)

**Comment by TimMcCool** [comment]
**user session.get_user instead of scratch3.get_user and use session.get_project instead of scratch3.get_project**

If Project / Studio / User objects are created using scratch3.get_project() / scratch3.get_studio() / scratch3.get_user(), they can’t be used to perform action that require a session. Use scratch3.Session.connect_project() / scratch3.Session.connect_user() / scratch3.Session.connect_studio() instead. (https://scratchattach.readthedocs.io/en/latest/scratchattach.html#scratchattach.exceptions.Unauthenticated)

**Comment by DebugDungeon** [comment]
oh
