### ISSUE TITLE
(Documentation) Forgot to add ’client.run(data_from_websocket=True)’

### ISSUE THREAD

**Issue by mas6y6** [TimMcCool/scratchattach#150]
^^

**Comment by DebugDungeon** [comment]
@TimMcCool pls fix this otherwise people will get confused

**Comment by TimMcCool** [comment]
data_from_websocket is True by default

**Comment by mas6y6** [comment]
Just to let you know that when this scratch cloud crisis stops its best to add it

**Comment by TimMcCool** [comment]
added some info about it to the bottom of this section: https://github.com/TimMcCool/scratchattach/wiki/Cloud-Requests#advanced-features
