### ISSUE TITLE
Refactor the CR sprite in Sprite version 1.2.0

### ISSUE THREAD

**Issue by crashbandicootsthe1** [TimMcCool/scratchattach#151]
Nothing much. Just that the code is quite messy and needs a clean up. Add explanations of each block if needed

**Comment by crashbandicootsthe1** [comment]
If you are bored, here is the average CR sprite when the project is shared
![Screenshot 2023-10-26 7 47 07 AM](https://github.com/TimMcCool/scratchattach/assets/144353514/0dadf155-afac-41f6-bc82-4bec0f51b902)

**Comment by TimMcCool** [comment]
I won't do this, at least not for now
