### ISSUE TITLE
Get a project's JSON given it's ID

### ISSUE THREAD

**Issue by crashbandicootsthe1** [TimMcCool/scratchattach#154]
### I know there are many issues about this, but this issue's name is the perfect method of uploading projects.

```
project.get_json("project_id")
```
Returns the project's JSON.

```
project.load_json("variable with json", "connected project id")
```
Loads the project ID's JSON, given this JSON is stored in a variable.

I hope this helps you TimMcCool...

![backdrop1](https://github.com/TimMcCool/scratchattach/assets/144353514/1617d620-ca1f-481d-9916-9057c136141f)

**Comment by TimMcCool** [comment]
Nice suggestions. I will add that when I have time

**Comment by TimMcCool** [comment]
Hi. Am I allowed to use the picture you provided as scratchattach logo? with credit ofc

**Comment by crashbandicootsthe1** [comment]
> Hi. Am I allowed to use the picture you provided as scratchattach logo? with credit ofc. Your suggestion will be added soon

Yes you can.

**Comment by TimMcCool** [comment]
Added `project.upload_json_from("project_id")` - this will upload the project json from the project with id "project_id" to the project represented by the project object
