### ISSUE TITLE
The _request status variable stays on TIMEOUT

### ISSUE THREAD

**Issue by gamecraft312** [TimMcCool/scratchattach#157]
import scratchattach as scratch3

session = scratch3.login("--", "--")
conn = session.connect_cloud("929934092")

client = scratch3.CloudRequests(conn)

@client.request
def ping():
    print("ping request received")
    return "pong"

@client.event
def on_ready():
    print("request handler is running")

client.run()

**Comment by JiushengChen** [comment]
Met the same problem. Set timeout_after to bigger value doesn't help. Found if I use the project owner account to login, it works even when server is in different machine. Timeout only happens when login using other accounts.

**Comment by TimMcCool** [comment]
> Met the same problem. I make the python script running in a cloud machine (https://scratch.mit.edu/projects/933459770/). Scratch client set timeout_after to bigger value doesn't help. Found if I use the project owner account to login, it works even when server is in different machine. Timeout only happens when login using other accounts. So it means it can't be shared to other people to use.

It looks like the problem is not happening anymore because I went to your project and the problem didn't occur
