### ISSUE TITLE
Variable Showing as None

### ISSUE THREAD

**Issue by YahyaBotMaker** [TimMcCool/scratchattach#158]
Hello, 

If I run the project and try to get the variable, when I print it, it returns as None. I didn't mind that first but then the entire file doesn't run as expected because it doesn't give the value.  . I tried many methods.

value = scratch3.get_var("project", "variable")
print(value)

This is the code I used, I checked the scratch project and it is not empty. 

I am running the code in VSCODE

Edit: I just read the announcement and there was post similar to this. Is it somehow connected to it? If so is it possible to bypass it or something?

**Comment by programORdie2** [comment]
This is becouse the scratch cloudlogs are down currently.

**Comment by TimMcCool** [comment]
Yes, scratch3.get_var isn’t working atm because the clouddata logs are down atm.

**Comment by YahyaBotMaker** [comment]
> Yes, scratch3.get_var isn’t working atm because the clouddata logs are down atm.

Oh! Alright!

**Comment by GitbyteMaster** [comment]
Scratch code sure is frustrating...

**Comment by policerdarm111-github** [comment]
> Yes, scratch3.get_var isn’t working atm because the clouddata logs are down atm.

thanks, i just had the same problem

**Comment by GitbyteMaster** [comment]
Made my own script that can fully load Scratch Cloud vars, and the logs are indeed working, so what's going on?

**Comment by RC9910-Scratch** [comment]
> Made my own script that can fully load Scratch Cloud vars, and the logs are indeed working, so what's going on?

The could logs are FINALLY working again, about 2 months ago they weren't

**Comment by GameGrusher** [comment]
> > Made my own script that can fully load Scratch Cloud vars, and the logs are indeed working, so what's going on?
> 
> The could logs are FINALLY working again, about 2 months ago they weren't

They are? Finally!!!

Also, I am YahyaBotMaker. You can close this issue.

**Comment by RC9910-Scratch** [comment]
> > > Made my own script that can fully load Scratch Cloud vars, and the logs are indeed working, so what's going on?
> > 
> > 
> > The could logs are FINALLY working again, about 2 months ago they weren't
> 
> They are? Finally!!!
> 
> Also, I am YahyaBotMaker. You can close this issue.

I can't close this issue, but the original creator can (your other acc)

**Comment by GameGrusher** [comment]
> I can't close this issue, but the original creator can (your other acc)

oh, alright. I thought you could close the issue... lol.

**Comment by YahyaBotMaker** [comment]
I am closing this; the issue has been resolved.
