### ISSUE TITLE
TurboWarp project IDs for cloud variable connections must be numbers

### ISSUE THREAD

**Issue by PPPDUD** [TimMcCool/scratchattach#164]
Whenever you try to initiate a TurboWarp cloud variable connection with `conn = scratch3.connect_tw_cloud("PPPDUD-example")`, ScratchAttach 1.5.7 returns the following error: `ValueError: invalid literal for int() with base 10: 'PPPDUD-example'`.

This is problematic, since [you are recommended to use non-numerical custom project IDs](https://docs.turbowarp.org/cloud-variables).

**Comment by TimMcCool** [comment]
You can use non-numerical custom project IDs with `conn = scratch3.TwCloudConnection(project_id="projectid")`. For the other methods to connect to turbowarp cloud it doesn't seem to work, will be fixed

**Comment by TimMcCool** [comment]
fixed
