### ISSUE TITLE
Wiki Error: scratchattach - Issues with CloudRequest and scratch3.TwCloudRequests

### ISSUE THREAD

**Issue by manogames** [TimMcCool/scratchattach#165]
There is an error in the scratchattach wiki in the CloudRequest section. The wiki suggests using 'client = scratch3.TwCloudRequests(conn)' as the client for the cloudrequest server when needed for use in turbowarp. However, the 'scratch3.TwCloudRequests' function does not actually exist in the Python library, and the program fails to execute.

Is there a solution to this error or an alternative I can use? I have my turbowarp cloud server on localhost, and I want to have cloudrequest also on localhost, all together to have a local program that uses Python as the backend and scratch as the frontend.

In fact, using the 'scratch3.CloudRequests' function, I manage to run the program in a loop, and the cloudrequest user joins the room. However, no request is accepted on the server, and the following appears in the log:

[2023-12-29T19:32:55.492Z] info: [::1 "cloud" in 945204927] Joined room (peers: 1)
[2023-12-29T19:32:55.519Z] info: [::1 "cloud" in 945204927] Connection closed: code 1006

I think that since the client it uses is 'scratch3.CloudRequests,' it does not allow a connection to turbowarp and automatically exits the room. The projectid is a shared cloudrequest template on scratch.

Is there something that can work for my case?
![Screenshot_20231229_141229](https://github.com/TimMcCool/scratchattach/assets/102007014/0706e7cc-8440-4ad3-afc6-e1fcd7952f49)
![Screenshot_20231229_141312](https://github.com/TimMcCool/scratchattach/assets/102007014/6aca745b-e42c-4f93-a2e8-c6807fcf5e2a)

**Comment by RC9910-Scratch** [comment]
What's your code?

**Comment by manogames** [comment]
> What's your code?
My code is the cloud request template from the documentation with the necessary modifications for turbowarp.
`import scratchattach as scratch3
from scratchattach import *

conn = scratch3.TwCloudConnection(project_id = "945204927", username="cloud",cloud_host="ws://localhost:9080") 

client = scratch3.TwCCloudRequests(conn)

@client.request
def ping(): #called when client receives request
    print("Ping request received")
    return "pong" #sends back 'pong' to the Scratch project

@client.event
def on_ready():
    print("Request handler is running")

@client.event
def on_unknown_request(request):
    print("Received unknown request", request.name, request.requester, request.arguments, request.timestamp, request.id)

client.run() #make sure this is ALWAYS at the bottom of your Python file`

**Comment by RC9910-Scratch** [comment]
Try removing the `from scratchattach import *' line from the code, using it with `import scratchattach as scratch3` could make you have 2 instances of the scratchattach module, which could cause the error

**Comment by manogames** [comment]
> Try removing the `from scratchattach import *` line from the code, using it with `import scratchattach as scratch3` could make you have 2 instances of the scratchattach module, which could cause the error

I had placed it as an attempt to make it work, but even removing it, the following errors still occur.
```
Traceback (most recent call last):
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/scratchattach/_cloud.py", line 88, in _connect
    self.websocket.connect(
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/websocket/_http.py", line 141, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/websocket/_http.py", line 228, in _open_socket
    raise err
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/websocket/_http.py", line 205, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mano/scratchattach/main.py", line 3, in <module>
    conn = scratch3.TwCloudConnection(project_id = "945204927", username="cloud",cloud_host="ws://localhost:9080") 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/scratchattach/_cloud.py", line 17, in __init__
    self._connect(cloud_host=cloud_host)
  File "/home/mano/scratchattach/venv/lib/python3.11/site-packages/scratchattach/_cloud.py", line 93, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError
```

**Comment by manogames** [comment]
> Try removing the `from scratchattach import *` line from the code, using it with `import scratchattach as scratch3` could make you have 2 instances of the scratchattach module, which could cause the error

I've been reviewing the library code, and I found the TwCloudRequest class in `cloudrequest.py`. Its full name is `scratchattach.cloud_requests.TwCloudRequest`. However, when using `scratch3.cloud_requests.TwCloudRequests(conn)`, it doesn't detect it for some strange reason. I feel like that module is not being imported. When running the program, I get the following error:

```
Traceback (most recent call last):
  File "/home/mano/scratchattach/main.py", line 5, in <module>
    client = scratch3.cloud_requests.TwCloudRequests(conn)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scratchattach' has no attribute 'cloud_requests'. Did you mean: '_cloud_requests'?
```

So, I decided to change it as suggested (_cloud_request), but now I get the following error:

```
Traceback (most recent call last):
  File "/home/mano/scratchattach/main.py", line 5, in <module>
    client = scratch3._cloud_requests.TwCloudRequests(conn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scratchattach._cloud_requests' has no attribute 'TwCloudRequests'. Did you mean: 'CloudRequests'?
```

How can I correctly import this class? Overall, when reviewing the library code, everything seems to be fine. The class inherits from CloudRequest, as I assume it should, so I don't understand what is really happening.

**Comment by PPPDUD** [comment]
Are you using the latest version of ScratchAttach?

**Comment by manogames** [comment]
> Are you using the latest version of ScratchAttach?

Yes, indeed, I installed the latest version of the library on that same day.

**Comment by RC9910-Scratch** [comment]
Maybe reinstall scratchattach? (`pip uninstall scratchattach` then `pip install -U scratchattach`)

**Comment by manogames** [comment]
> Maybe reinstall scratchattach? (`pip uninstall scratchattach` then `pip install -U scratchattach`)

No, it still doesn't work

**Comment by RC9910-Scratch** [comment]
another question: Is there any file in the directory that you're running the main scripts that's called `scratchattach.py`?

**Comment by manogames** [comment]
> another question: Is there any file in the directory that you're running the main scripts that's called `scratchattach.py`?

No, the only script in that directory is main.py

**Comment by manogames** [comment]
> another question: Is there any file in the directory that you're running the main scripts that's called `scratchattach.py`?

I've been thoroughly reviewing everything, trying to figure out what I can do. In version 1.0.4 of scratchattach, it does detect TwCloudRequest, and the code runs successfully. However, it doesn't detect any requests now; it seems not to be working. I even tried using the cloudrequest version from 1.0.4, but I couldn't get the requests to work.

**Comment by TimMcCool** [comment]
try reinstalling v1.5.7

**Comment by manogames** [comment]
> try reinstalling v1.5.7

The code now runs, but it doesn't detect any requests. When attempting to make a request, it exits the room on the cloud server after a while. This is my code:


```python
import scratchattach as scratch3

conn = scratch3.TwCloudConnection(project_id="945685081", username="cloud", cloud_host="ws://localhost:9080")

client = scratch3.TwCloudRequests(conn)

@client.request
def ping():  # called when the client receives a request
    print("Ping request received")
    return "pong"  # sends back 'pong' to the Scratch project

@client.event
def on_ready():
    print("Request handler is running")

@client.event
def on_unknown_request(request):
    print("Received unknown request", request.name, request.requester, request.arguments, request.timestamp,
          request.id)

client.run()  # make sure this is ALWAYS at the bottom of your Python file
```


And this is the log from the cloud server:

```
[2024-01-02T00:11:44.939Z] info: [::1 "cloud" in 945685081] Connection closed: code 1006
[2024-01-02T00:11:44.943Z] info: [::1 "cloud" in 945685081] Joined room (peers: 1)
[2024-01-02T00:12:11.075Z] info: Pinging 1 client...
[2024-01-02T00:12:38.954Z] info: [::ffff:127.0.0.1] Connection opened
[2024-01-02T00:12:38.988Z] info: [::ffff:127.0.0.1 "player" in 945685081] Joined room (peers: 2)
[2024-01-02T00:12:41.075Z] info: Pinging 2 clients...
[2024-01-02T00:12:41.076Z] info: [::1 "cloud" in 945685081] Timed out: no pong
[2024-01-02T00:12:41.076Z] info: [::1 "cloud" in 945685081] Connection closed: code 1006
[2024-01-02T00:13:11.075Z] info: Pinging 1 client...
```
