### ISSUE TITLE
Client.request functions won't return values to the Scratch project when executed in the script

### ISSUE THREAD

**Issue by crashbandicootsthe1** [TimMcCool/scratchattach#166]
### This is what I mean by "Executed in the script" (this is an example, not an issue with my code):

```
import scratchattach as scratch3
from threading import Thread
import time
import os

ready = 0

session = scratch3.Session(os.environ["SESSION_ID"], username="username")
conn = session.connect_cloud(123456789)
client = scratch3.CloudRequests(conn)


@client.request
def ping():
    return "pong"

@client.event
def on_ready():
    global ready
    ready = 1
    print("Request handler is running")

def thread_loop():
    while True:
        time.sleep(15)
        if ready == 1:
            ping() # This line specifically won't return "pong" to Scratch
            break

thread = Thread(target=thread_loop)
thread.start()
client.run()
```

It should also delete all items from the response list like a traditional "client.request" function.

I will edit the code if needed.

Fix this in a smaller update if needed. If it was an intentional feature, tell me.

**Comment by manogames** [comment]
1. The while loop is placed before `client.run()`, therefore, being an endless loop, it will never allow `client.run()` to execute, and ClientRequest will never be served.

2. Another thing I noticed is that you are calling the `ping()` function from Python in the while loop. I don't understand why, but I assume you want to send information to Scratch. If so, it won't work. You need to first make a request from the Scratch client and then send information from Python.

For item 1, I suggest solving it by running ClientRequest as a thread or threads.

**Comment by TimMcCool** [comment]
Cloud requests don't work like that. They'll only send back their output when they're called from the Scratch project. You can't call them server-side, then they won't send anything to the Scratch project (which kinda makes sense, because which Scratcher should receive the response data if there's noone who called the request?)
