### ISSUE TITLE
long variable set

### ISSUE THREAD

**Issue by gixtuh** [TimMcCool/scratchattach#167]
```python
import scratchattach as scratch3

id = "914049578"

user = scratch3.login("Policerdarm111", "2************h2")
clouds = user.connect_cloud(id)
project = scratch3.get_project(id)

while True:
    clouds.set_var("test", project.loves)
```

works fine but the "☁ test" variable changes REALLY slow, @TimMcCool, do you know why?

**Comment by crashbandicootsthe1** [comment]
**while True:** can rate-limit you and ban you from using the API for a few minutes. Try adding a 15-second delay between each change. I will provide more steps to enhance speed when you comment back

**Comment by TimMcCool** [comment]
> ```python
> import scratchattach as scratch3
> 
> id = "914049578"
> 
> user = scratch3.login("Policerdarm111", "2************h2")
> clouds = user.connect_cloud(id)
> project = scratch3.get_project(id)
> 
> while True:
>     clouds.set_var("test", project.loves)
> ```
> 
> works fine but the "☁ test" variable changes REALLY slow, @TimMcCool, do you know why?

You have to put `project.update()` in the while True loop, or else the project.loves attribute won't update.

```py
while True:
    clouds.set_var("test", project.loves)
    project.update()
```
