### ISSUE TITLE
Invalid Value when returning Boolean

### ISSUE THREAD

**Issue by ziqiangao** [TimMcCool/scratchattach#168]
using cloud requests when returning True or False, it returns something like 'True.38328' which is invalid

```python
@client.request
def set(i):
    print("request received")
    if is_float(i):
        ob = open("value.txt", "w")
        ob.write(str(float(i)))
        ob.close()
        return True
    else:
        return False
```

one workaround is to wrap it in quotes

**Comment by RC9910-Scratch** [comment]
I don't think cloudrequests support booleans, as `True` and `False` aren't in the encoder

**Comment by TimMcCool** [comment]
Yeah, convert the boolean to a string before return it: `str(True)`. Or simply return 1 for True and 0 for False. Returning booleans is not supported
