### ISSUE TITLE
idk 

### ISSUE THREAD

**Issue by tympanicblock61** [TimMcCool/scratchattach#17]
![image](https://user-images.githubusercontent.com/99092380/172021787-6e8d3c8f-0532-436c-b30c-b9380582fa76.png)

**Comment by noverd** [comment]
Show full error

**Comment by noverd** [comment]
please

**Comment by TimMcCool** [comment]
> ![image](https://user-images.githubusercontent.com/99092380/172021787-6e8d3c8f-0532-436c-b30c-b9380582fa76.png)

You can't login from replit because Scratch blocked some of replit's ip adresses. A solution would be to run the code on your computer, or to try cookie login

**Comment by tympanicblock61** [comment]
k
