### ISSUE TITLE
Add an option to make threads used for cloud requests daemon

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#170]
Maybe you could add a keyword argument `daemon` that would make a thread used for the cloud requests daemon.

**Comment by TimMcCool** [comment]
Will maybe be added. For now, you can do this:
```py
from threading import Thread
...
Thread(target=client.run, daemon=True).start()
```

**Comment by TheCommCraft** [comment]
Of course, but there is also support for a thread

Tim ***@***.***> schrieb am Fr., 26. Jan. 2024, 14:22:

**Comment by TimMcCool** [comment]
added
