### ISSUE TITLE
Readd scratchattach.cloud_requests.CloudRequests.get_requester()

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#171]
The cloudmonitor is back

**Comment by programORdie2** [comment]
> The cloudmonitor is back

Already a few weeks.

**Comment by TheCommCraft** [comment]
but the features it's required for aren't back still

programORdie ***@***.***> schrieb am So., 28. Jan. 2024,
21:27:

**Comment by TimMcCool** [comment]
the method should still be working
