### ISSUE TITLE
Support for sending = in a request

### ISSUE THREAD

**Issue by Stoutscientist** [TimMcCool/scratchattach#176]
Basically I'm trying to request data from the server and the server will spit out code which contains a =, but it doesn't seem to support that and will just replace it with a space.

**Comment by TimMcCool** [comment]
You can customize the encoder and add / remove characters: [https://github.com/TimMcCool/scratchattach/wiki#encoding--decoding](https://github.com/TimMcCool/scratchattach/wiki#encoding--decoding)
