### ISSUE TITLE
Question:About TwCloudConnection class and cloud_host

### ISSUE THREAD

**Issue by manogames** [TimMcCool/scratchattach#181]
Does the TwCloudConnection class need a cloud host with an SSL certificate?

**Comment by TimMcCool** [comment]
not sure. Maybe check turbowarp's docs on custom cloud hosts or simply try it out

**Comment by zaid1442011** [comment]
No it doesn't. I tested it.

**Comment by namtacs** [comment]
If you are using **wsS**, **you must use a self-signed certificate** or a free one from _Let's Encrypt_.
If you are using **ws (not secure)**, the **certificate is not needed**
By default the turbowarp node server is using ws.

If you need a secure server, you should **host a non-secure one behind an https (secure) reverse proxy**, like this: https://github.com/TurboWarp/cloud-server?tab=readme-ov-file#production-setup

For testing just use it in the ws mode.
