### ISSUE TITLE
Connect_user does not work!!!

### ISSUE THREAD

**Issue by discovery1104** [TimMcCool/scratchattach#184]
Connect_user does not work.

    user = scratch3.connect_user("griffpatch")
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scratchattach' has no attribute 'connect_user'

`import customtkinter as ctk
from scratchattach import session
import scratchattach as scratch3

def search_button_clicked():
    user = scratch3.connect_user("griffpatch") # Errors occur here.
    username_entry.pack_forget()
    username_label.pack_forget()
    search_button.pack_forget()
    result_label.configure(text=user.id)
    result_labela.configure(text=user.join_date)
app = ctk.CTk()
app.geometry("400x200")

username_label = ctk.CTkLabel(app, text="Usernameを入力")
username_label.pack()   

username_entry = ctk.CTkEntry(app, placeholder_text="griffpatch")
username_entry.pack()

search_button = ctk.CTkButton(app, text="検索", command=search_button_clicked)
search_button.pack()

result_label = ctk.CTkLabel(app, text="")
result_label.pack()

result_labela = ctk.CTkLabel(app, text="")
result_labela.pack()

app.mainloop()
`

**Comment by TimMcCool** [comment]
either use `user = scratch3.get_user("griffpatch")`. Or, if you want to perform actions that require a login (like user.follow()), use:
```py
session = scratch3.login("username", "password")
user = session.get_user("griffpatch")
```
`scratch3.connect_user` does not exist

**Comment by discovery1104** [comment]
Thank you so much.
