### ISSUE TITLE
project.update not realtime

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#194]
I think the headers are not correct. This is an example raw request needed to get a realtime update:
```
GET /projects/1000531175 HTTP/2
Host: api.scratch.mit.edu
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
Accept: */*
Accept-Language: en, en;q=0.8
Accept-Encoding: gzip, deflate, br
X-Token: 236e5101158f44a68dc62f71291ddd0f:ya_cJ5XM27VwzKL3TI09KXIw-dI
Origin: https://scratch.mit.edu
Connection: keep-alive
Referer: https://scratch.mit.edu/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```

**Comment by TheCommCraft** [comment]
headers = {
    'Accept-Language': 'en, en;q=0.8',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'Origin': 'https://scratch.mit.edu',
    'Pragma': 'no-cache',
    'Referer': 'https://scratch.mit.edu/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'TE': 'trailers',
    'X-Token': '236e5101158f44a68dc62f71291ddd0f:ya_cJ5XM27VwzKL3TI09KXIw-dI',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0',
}

**Comment by TimMcCool** [comment]
I'll add the `Cache-Control: no-cache` header to the requests to prevent server-side hashing (afaik there is no server-side caching for this API by default, but to ensure this I will add the header). The other headers don't have any effect on the returned data tho
