### ISSUE TITLE
Pass integers in session.connect_user() as user ID values

### ISSUE THREAD

**Issue by slime-lol** [TimMcCool/scratchattach#199]
I am trying to make a script to get a random user, but i just realized that the `session.connect_user()` doesn't pass user IDs, it assumes that any string or integer value is a username.

**Comment by TheCommCraft** [comment]
It's not possible

**Comment by TheCommCraft** [comment]
try searching for a random studio or project and then get its auther

**Comment by TimMcCool** [comment]
the scratch API doesn't allow getting users by id

**Comment by TimMcCool** [comment]
Actually there is a way of getting a user by id, and it will be added in the next update

**Comment by TimMcCool** [comment]
scratchattach 2.0 is released now. it has the `user = session.connect_user_by_id(user_id)` method
