### ISSUE TITLE
Ghost requests are back.

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#200]
#130 is back I think

**Comment by 1hercules** [comment]
When does this bug occur?

**Comment by TheCommCraft** [comment]
Whenever the program starts anew I'd say

**Comment by 1hercules** [comment]
hmm, weird I'm gonna take a look at the code

**Comment by crzylemon** [comment]
i had this too

**Comment by blazgocompany** [comment]
I believe this has nothing to do with `scratchattach` but is something with the scratch servers itself:

> See https://en.scratch-wiki.info/wiki/Cloud_Data

In October of 2016, the cloud infrastructure started to fail occasionally.  As a result, many multiplayer-focused projects did not work correctly. This has been attributed to the ever-increasing number of active users who are using cloud variables, with some projects sending up to 30 requests per cloud variable per second. This effectively "spammed" the cloud server with a load that couldn't be handled by the current infrastructure and shut it down.

As a temporary fix, cloud variables have switched to using a different polling method, which is more reliable but significantly slower. Furthermore, the polling interval time was increased, to prevent spam. <ins>**This new method works but may cause cloud variables to "rubber band" and reset to a previous value after it has been changed**</ins>, as well as making many multiplayer projects less "real-time" or completely breaking them in general.

I believe this "rubber-band" effect is causing these "ghost requests"

**Comment by TheCommCraft** [comment]
Yes, but this can be mitigated by ignoring initial cloud variable values

blazgocompany ***@***.***> schrieb am Mi., 4. Sept. 2024,
16:15:
