### ISSUE TITLE
no way to get a comment from its comment id (at least i think)

### ISSUE THREAD

**Issue by Eitan222** [TimMcCool/scratchattach#201]
from my knowledge, there is no way to get a comment from its id, which can be found if a comment's link is copied, and this could be useful for getting a comment from a comment link, and also can be useful for the get replies method too, which uses a comment id

**Comment by Eitan222** [comment]
also, there IS a way to get a comment from its id in the api (at least for projects) i've checked

**Comment by TimMcCool** [comment]
afaik it is possible to get project and studio comments by id, but not profile comments

**Comment by TimMcCool** [comment]
will maybe be added to scratchattach
