### ISSUE TITLE
Incorrect Error

### ISSUE THREAD

**Issue by kakeruzoku** [TimMcCool/scratchattach#202]
hello!

The three raise() functions in studio.py are not executed correctly.

Change in line 292, 307, and 323,
Before:
`raise(_exceptions.Unauthorized)`
After:
`raise(exceptions.Unauthorized)`

I used google translate. Thank you.

**Comment by TimMcCool** [comment]
Thanks, will be fixed soon

**Comment by kakeruzoku** [comment]
thank you!

**Comment by namtacs** [comment]
pls close

**Comment by kakeruzoku** [comment]
sorry I did.
