### ISSUE TITLE
How to check if user exists?

### ISSUE THREAD

**Issue by JustablockCode** [TimMcCool/scratchattach#205]
How to check if user exists?

**Comment by namtacs** [comment]
> How to check if user exists?

```python
try:
     user=scratch3.get_user("probablynonexistentusername")
except scratch3.exceptions.UserNotFound:
     print("User not found")
     user=None

if user is not None:
     print("User's about me:", user.about_me)
```

**Comment by JustablockCode** [comment]
> > How to check if user exists?
> 
> ```python
> try:
>      user=scratch3.get_user("probablynonexistentusername")
> except scratch3.exceptions.UserNotFound:
>      print("User not found")
>      user=None
> 
> if user is not None:
>      print("User's about me:", user.about_me)
> ```

thx
