### ISSUE TITLE
Make api request functions unlimited #206

### ISSUE THREAD

**Issue by namtacs** [TimMcCool/scratchattach#210]
Please check #206
Creating this because no one noticed

**Comment by TheCommCraft** [comment]
I don't think you need to remind them, they probably don't have the time
for it right now.

namtacs ***@***.***> schrieb am Mi., 22. Mai 2024, 16:39:

**Comment by namtacs** [comment]
but have time for making scratch games (in logs) and checking issues every day

**Comment by TimMcCool** [comment]
will be looked into and (at least partly) merged by the end of this week

**Comment by TimMcCool** [comment]
#206 has been checked and will be merged soon
