### ISSUE TITLE
Implement a Proper Way to Check “New Scratcher” Status

### ISSUE THREAD

**Issue by Are-You-a-Person** [TimMcCool/scratchattach#211]
For Scratchattach, it would be very helpful if there was a simple way to check if a particular user is a New Scratcher or Scratcher.

There is already code in Scratchattach that allows you to check your own account for the status but that it not helpful in my case.
`session.new_scratcher #Returns True if the associated account is a New Scratcher`

If added, it should probably look something like this.
`username.new_scratcher #Returns True if the username is a New Scratcher`

Currently, I have to make use of something like this to check if the account is less than 2 weeks old but this does not catch all New Scratchers.
`iso_date = session.connect_user(event.user).join_date`
`if (time.time() - (datetime.datetime.strptime(iso_date, "%Y-%m-%dT%H:%M:%S.%fZ").timestamp())) < 1209600):`
`    # code here…`

**Comment by TheCommCraft** [comment]
Good idea! This could be done with web scraping if nothing else works

Are-You-a-Person ***@***.***> schrieb am Do., 23. Mai 2024,
04:51:

**Comment by namtacs** [comment]
🚨️ hecker detected !!! bad person  (https://github.com/Are-You-a-Person/scratchSploit/tree/main/scripts) hacks

Anyway, the scratch api doesn't provide this, but
we can fetch it ourselves (in a hacky way):
```python
def is_new_scratcher(username):
    res=arc.scratch3.requests.get(f"https://scratch.mit.edu/users/{username}/").text
    group=res[res.rindex('<span class="group">'):][:70]
    return "new scratcher" in group.lower()
```
This code can break if scratch receives a very big update (never).
I'm providing help because I see you need this for your [ban_annoyances](https://github.com/Are-You-a-Person/ban_annoyances_2/blob/main/main.py) project and you understand the consequences of hacking.

**Comment by Ryan-shamu-YT** [comment]
![image](https://github.com/TimMcCool/scratchattach/assets/83490776/4255d96f-f8e3-40d5-9a8b-d2b9be6f4fda)

**Comment by namtacs** [comment]
ok

**Comment by Are-You-a-Person** [comment]
I will update the ban_annoyances code on my GitHub page since it’s extremely outdated; I fixed a bunch of issues with it over time and added improvements to make it more efficient at blocking hackers.

**Comment by TimMcCool** [comment]
user.is_new_scratcher() has been added in v1.3.7 (will be released in a few minutes)

**Comment by Ryan-shamu-YT** [comment]
Great!
