### ISSUE TITLE
(upcoming update) Enhance cloud requests by replacing busy-sleep event loop

### ISSUE THREAD

**Issue by TimMcCool** [TimMcCool/scratchattach#213]
Replacing the busy-sleep event loop currently used by scratchattach's cloud requests using either the Condition class of the threading module or by introducing asyncio to the library.
This will lower CPU usage.

**Comment by namtacs** [comment]
Great! Hoping for asyncio.
Also it would be great to have the simple cloud methods be async/non-blocking.

**Comment by TheCommCraft** [comment]
Good ideas!

**Comment by TheCommCraft** [comment]
You should either make asyncio optional or make it not affect what the user has to code

**Comment by TimMcCool** [comment]
> You should either make asyncio optional or make it not affect what the user has to code

It will be optional, I'm trying to avoid breaking changes when possible

**Comment by TheCommCraft** [comment]
So?

**Comment by TimMcCool** [comment]
> So?

Planned for August 2024
