### ISSUE TITLE
Scratch project response list is randomly (at least seems like randomly) displaying "Error: Check the Python console"

### ISSUE THREAD

**Issue by wvzack** [TimMcCool/scratchattach#214]
My python script is working completely fine and I have added print statements to make sure its working however sometimes the project is saying "Error: Check the Python console" or what is supposed to be displayed joined with "Error: Check the Python console".
I ran 20 tests and I will put what happened how many times:

You have 1000 dollar(s) (what is supposed to happen) 8x

Error: Check the Python consoleYou have 1000 dollar(s) 2x

Error: Check the Python console 7x

You have 1000 dollar(s)Error: Check the Python console 3x

And not a single of these requests had an error in the python console or terminal.
I am using scratchattach V1.7.3, Python 3.11.1, and the scratch project version 1.1.8

Thanks!

**Comment by TheCommCraft** [comment]
Is it perhaps possible that you have accidentally forgotten to stop running
an old version of the backend AND the newest?

wvzack ***@***.***> schrieb am Mo., 27. Mai 2024, 03:23:

**Comment by wvzack** [comment]
Will see I just shutdown my computer for the night so everything should of shutdown if it keeps happening I suspect its not that.

**Comment by JackAttack365** [comment]
Yes, I think so. If you press the re-run button on the bar that pops up, it terminates the current process running in the terminal and starts a new one. IDK if that's what you mean though. If you start another python debugger, I think they run concurrently.

**Comment by TheCommCraft** [comment]
> Will see I just shutdown my computer for the night so everything should of shutdown if it keeps happening I suspect its not that.
> 
> Edit: Okay it seems to be working now. Also a bit unrelated if you start a script on vsode with run and you press run again with a updated script does this cancel the first run? Thanks!!!

From my experience, the old script doesn't stop running directly until it is finished and only when it is finished the new starts running
