### ISSUE TITLE
'User' object has no attribute 'is_new_scratcher'

### ISSUE THREAD

**Issue by MilesWK** [TimMcCool/scratchattach#217]
Hello! I am using the `getuser()` function to get the name of a user, and then using `user.is_new_scratcher()` function but it gives me the error "'User' object has no attribute 'is_new_scratcher'." Am I doing something wrong?

**Comment by namtacs** [comment]
is_new_scratcher was added in 1.7.3, but your version is probably outdated.

Please update scratchattach by running the install command with the `-U` flag, like this:
`pip install -U scratchattach` (in console)

**Comment by MilesWK** [comment]
Good morning (for me),

Thanks for the response. It worked great! Thank you!
