### ISSUE TITLE
How do/can I package a scratchattach project using the turbowarp packager?

### ISSUE THREAD

**Issue by acesavagejr** [TimMcCool/scratchattach#219]
Hello Guys! I've been making a weather project that runs off of scratchattach, I've been wanting to make it an android app for personal use all my attemps have not worked many thanks!

Here's a console log:
![image_2024-06-30_225111251](https://github.com/TimMcCool/scratchattach/assets/85138593/99015f00-4892-4e7f-8439-7d02d30f4fad)

I see its trying to connect but fails maybe scratches server is rejecting to connect?

**Comment by TheCommCraft** [comment]
You need to connect to the corresponding turbowarp project

**Comment by acesavagejr** [comment]
> You need to connect to the corresponding turbowarp project

Thanks!
