### ISSUE TITLE
Set varibles in multiple ones without a request

### ISSUE THREAD

**Issue by Zocker-Welt** [TimMcCool/scratchattach#224]
It would be cool if u could have a string and split it to multiple variables without a request

**Comment by hcr5** [comment]
So do you mean we can split a string into multiple variables, like `"var1=10;var2=20"`?

```python
import scratchattach as scratch3

session = scratch3.login("username", "password")
conn = session.connect_cloud("projectid")

vars_string = "var1=10;var2=20"
conn.set_vars_from_string(vars_string)
```
I don't know if this is what you mean.

**Comment by TimMcCool** [comment]
I'll check whether this is possible

**Comment by TimMcCool** [comment]
Implemented in the v2 branch
#242
