### ISSUE TITLE
Incosistent cloud variable setting

### ISSUE THREAD

**Issue by yamcrunchy** [TimMcCool/scratchattach#232]
I have a python script and everything has been configured according to the docs. 
The problem is sometimes the cloud variables are set but sometimes nothing happens. This can happen spontaneously and erratically. Especially where I need a chain of back to back communication between the project and my python file.

**Comment by TheCommCraft** [comment]
Don't do that

li371359001 ***@***.***> schrieb am Mi., 28. Aug. 2024, 07:59:

**Comment by TheCommCraft** [comment]
Whatever was the second reply, don't use its advice. A encrypted archive cannot be scanned by antivirus software. This is a trojan.

**Comment by TheCommCraft** [comment]
That program was going to infect your c compiler

zaedyn ***@***.***> schrieb am Mi., 28. Aug. 2024, 07:55:

**Comment by yamcrunchy** [comment]
Thanks for looking out for me :)

**Comment by TheCommCraft** [comment]
Could you please send your code (do *NOT* include  passwords or similar) and the error

**Comment by yamcrunchy** [comment]
https://github.com/yamcrunchy/scratchpedia
yea here it is
forgive the messiness i code something like once a year

**Comment by TimMcCool** [comment]
> I have a python script and everything has been configured according to the docs. The problem is sometimes the cloud variables are set but sometimes nothing happens. This can happen spontaneously and erratically. Especially where I need a chain of back to back communication between the project and my python file.

This is fixed in scratchattach 2.0.
