### ISSUE TITLE
ScratchHost

### ISSUE THREAD

**Issue by SpyC0der77** [TimMcCool/scratchattach#233]
They can't afford to maintain scratchhost :(

**Comment by TheCommCraft** [comment]
If you use it, they just might

SpyC0der77 ***@***.***> schrieb am Di., 3. Sept. 2024, 00:40:

**Comment by blazgocompany** [comment]
> If you use it, they just might

I would think the opposite.

There are still multiple ways to host your Python projects, @SpyC0der77. You can use AWS EC2, and the Google Compute Engine. Another option is to use GitHub Actions, although it is harder to set up and is not very customizable.

**Comment by TheCommCraft** [comment]
There are ads

blazgocompany ***@***.***> schrieb am Mi., 4. Sept. 2024,
00:59:

**Comment by SpyC0der77** [comment]
Oh then ima turn off my ad blocker for that website

**Comment by TheCommCraft** [comment]
That isn't allowed on Github Actions, I would advise against it

blazgocompany ***@***.***> schrieb am Mi., 4. Sept. 2024,
16:04:

**Comment by Ryan-shamu-YT** [comment]
Guys, ScratchHost is not shutting down. It is just one of our nodes might be shutting down, the rest we can afford, but who knows, there is still about 20 days to go, we might be able to get enough money to keep internode running.

**Comment by Ryan-shamu-YT** [comment]
The servers on Zimnode will still continue

**Comment by SpyC0der77** [comment]
oh ok. thx for the info

**Comment by Ryan-shamu-YT** [comment]
> oh ok. thx for the info

No problem.

**Comment by blazgocompany** [comment]
> That isn't allowed on Github Actions, I would advise against it

Do you know exactly where it says that in the ToC or something. If it does, I may move eveything over to ScratchHost

**Comment by SpyC0der77** [comment]
wait on scratchhost i no longer see the store option

**Comment by blazgocompany** [comment]
@SpyC0der77, Yea.. I don't see it either..

**Comment by Ryan-shamu-YT** [comment]
The store will open 6/7 September (Depends on your timezone)

**Comment by TheCommCraft** [comment]
It's temporarily disabled

blazgocompany ***@***.***> schrieb am Mi., 4. Sept. 2024,
23:33:

**Comment by TheCommCraft** [comment]
I have asked them if I may reenable it

Simon Gilde ***@***.***> schrieb am Do., 5. Sept. 2024, 07:08:

**Comment by SpyC0der77** [comment]
> The store will open 6/7 September (Depends on your timezone)

So tomorrow?

**Comment by Ryan-shamu-YT** [comment]
We are back now!

**Comment by SpyC0der77** [comment]
What are some good refferal links to get credits other than just afking

**Comment by Ryan-shamu-YT** [comment]
> What are some good refferal links to get credits other than just afking

You can invite other users to ScratchHost with a referral link and get some credits, you can also do surveys if available for you (Surveys are not always available!)
And we plan to add other ways soon!

**Comment by TheCommCraft** [comment]
For a limited amount of time, you can use coupon code "scratch" for extra credits

**Comment by TheCommCraft** [comment]
Maybe a bit late, but Internode is shutting down tomorrow!!!

**Comment by Ryan-shamu-YT** [comment]
A new node is opening btw.

**Comment by TheCommCraft** [comment]
But to be sure, maybe you should download your servers

**Comment by Ryan-shamu-YT** [comment]
Yes

**Comment by SpyC0der77** [comment]
I cant create a server, it says internal server error

**Comment by blazgocompany** [comment]
@SpyC0der77, does it say "500"?

**Comment by SpyC0der77** [comment]
yes

**Comment by SpyC0der77** [comment]
yes it does

**Comment by blazgocompany** [comment]
Then they probably messed up something....

**Comment by SpyC0der77** [comment]
Yeah.

**Comment by georg-stone** [comment]
Is it even possible to host Python with persistence on Github Actions?

**Comment by blazgocompany** [comment]
@georg-stone, It's possible, but you need to schedule a cron to run every 6 hours, because it stops after 6 hours, but if you program is able to gracefully stop and restart, it may work.

**Comment by SpyC0der77** [comment]
What is a cron?

**Comment by TheCommCraft** [comment]
A schedule trigger

SpyC0der77 ***@***.***> schrieb am Do., 17. Okt. 2024, 14:07:

**Comment by SpyC0der77** [comment]
Uhm, i can create infinite servers for free, and it keeps saying installing on all of my servers

**Comment by georg-stone** [comment]
Infinite servers on what?

**Comment by SpyC0der77** [comment]
ScratchHost

**Comment by TheCommCraft** [comment]
ScratchHost has sadly shut down. Go to the website to find steps to recover information.
