### ISSUE TITLE
Help with ScratchHost!

### ISSUE THREAD

**Issue by blazgocompany** [TimMcCool/scratchattach#238]
I am trying to make a Python Flask app using ScratchHost, but It keeps saying my account is not verified. So I stopped using it. Then I forgot my password. now I am trying to reset my password but it doesn't send an email. Even creating a new account doesn't work. Also how do I get a domain for my Flask app. I can use neocities, but how do I make a connection between neocities and ScratchHost?

**Comment by TheCommCraft** [comment]
You need to click the link in the verification email to verify your account
and only then can you use it the reset your password

blazgocompany ***@***.***> schrieb am Do., 12. Sept. 2024,
23:32:

**Comment by blazgocompany** [comment]
Ok. It was in my junk!

**Comment by blazgocompany** [comment]
And what domain will I get?

**Comment by blazgocompany** [comment]
and WHY does a DATABASE cost FIVE THOUSAND credits?????????

**Comment by TheCommCraft** [comment]
Databases are not supported, but you can get a database from silly
development

blazgocompany ***@***.***> schrieb am Fr., 13. Sept. 2024,
22:47:
