### ISSUE TITLE
text = text.split("Followers (")[1]

### ISSUE THREAD

**Issue by Zocker-Welt** [TimMcCool/scratchattach#239]
```
Traceback (most recent call last):
  File "C:\Users\Misha\AppData\Local\Programs\Python\Python312\Lib\site-packages\scratchattach\cloud_requests.py", line 116, in call_request
    output = req_obj["on_call"](*arguments) # Calls the request function and saves the function's returned data in the output variable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Misha\Desktop\Scratch Library\cat_stats.py", line 63, in user_stats
    user_stats.append(str(user.follower_count())) # Follower count
                          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Misha\AppData\Local\Programs\Python\Python312\Lib\site-packages\scratchattach\user.py", line 180, in follower_count
    text = text.split("Followers (")[1]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
This is not my error. Why does this happen, I re-installed scratchattach

**Comment by TheCommCraft** [comment]
It means that you might be ip-blocked or that for some reason your profile
page doesn't have a Follower count

Zocker-Welt ***@***.***> schrieb am Mo., 16. Sept. 2024,
18:35:

**Comment by Zocker-Welt** [comment]
Why would scratch ip ban me????

**Comment by TimMcCool** [comment]
Maybe it fails because the followers page is returned in another language (shouldn't happen tho, since the langauge cookie is set to en)

**Comment by TheCommCraft** [comment]
Yeah, that's what I thought, so it must be an ipban or maybe the person
doesn't have any followers yet

Tim ***@***.***> schrieb am Mi., 25. Sept. 2024, 14:09:

**Comment by TimMcCool** [comment]
Does the problem still happen?
