### ISSUE TITLE
How to save session?

### ISSUE THREAD

**Issue by blazgocompany** [TimMcCool/scratchattach#246]
I login to scratch using `scratch3.login`, which returns a session. How can I save that session so that I don't have to repeatedly sign in.

**Comment by TimMcCool** [comment]
save the session id: `session.session_id`

the next time you run your program, log in using the session id:`
```py
session = scratch3.Session("session_id")
```

**Comment by TimMcCool** [comment]
For scratchattach 2.0.0, see https://github.com/TimMcCool/scratchattach/wiki/Documentation#logging-in
