### ISSUE TITLE
Cloud variables not allowed to be scraped

### ISSUE THREAD

**Issue by PlayfulMathematician** [TimMcCool/scratchattach#248]
This isn't an error. But it is against the robots.txt of scratch. https://scratch.mit.edu/robots.txt

**Comment by TheCommCraft** [comment]
I am pretty sure that they are not being scraped. The api is used

undeterminstic ***@***.***> schrieb am Mi., 9. Okt. 2024,
16:11:

**Comment by TimMcCool** [comment]
Cloud variables are not being web-scraped. They are either received from the websocket or from the cloudmonitor API. See:

https://github.com/TimMcCool/scratchattach/blob/ed7fc04c2c3f1460f804fc11a159c4a784d8e720/scratchattach/cloud/cloud.py#L37

https://github.com/TimMcCool/scratchattach/blob/ed7fc04c2c3f1460f804fc11a159c4a784d8e720/scratchattach/cloud/_base.py#L239

https://github.com/TimMcCool/scratchattach/blob/ed7fc04c2c3f1460f804fc11a159c4a784d8e720/scratchattach/eventhandlers/cloud_recorder.py#L12

**Comment by Zaydiscool777** [comment]
what's baiduspider? (btw \@zcs1393793)

**Comment by TheCommCraft** [comment]
A Chinese webcrawler for baidu

zaydm ***@***.***> schrieb am Sa., 12. Okt. 2024, 04:09:
