### ISSUE TITLE
How to update to 2.0?

### ISSUE THREAD

**Issue by banddans** [TimMcCool/scratchattach#252]
On pip it says 1.7.4 is the lastest version, also when i reinstall it I don't get the new features. How do i update?

**Comment by TimMcCool** [comment]
2.0 is not released yet, but will be released today

**Comment by SpyC0der77** [comment]
when today?

**Comment by SpyC0der77** [comment]
Also, when will you update the docs?

**Comment by SpyC0der77** [comment]
i got the new version from the repo

**Comment by TimMcCool** [comment]
2.0.0 is released now. Use `pip install -U scratchattach` to update

**Comment by SpyC0der77** [comment]
nice! What time zone are you in, because yesterday you said it would be released yesterday, but rn for me it is today not yesterday if  u nkow what i mean

**Comment by TimMcCool** [comment]
I'm in UTC+2. I unfortunately wasn't able to finish the docs yesterday.

**Comment by TimMcCool** [comment]
There was a pretty bad bug regarding cloud events (and all features based on cloud events) in scratchattach 2.0.0, so please update to at least v2.0.5.

versions 2.0.0 to 2.0.4 have been deleted
