### ISSUE TITLE
Why is this returning empty brackets?

### ISSUE THREAD

**Issue by wvzackscratch** [TimMcCool/scratchattach#255]
This may be a problem with scratchattach or I made a mistake I have overlooked.
I am getting the first comment from [this project](https://scratch.mit.edu/projects/1075070791/l) using this script: 
```
import scratchattach as sa

session = sa.login("wvzacktest", "##############") #Returns a sa.Session object

project = session.connect_project("1075070791") # Returns a sa.Project object
print(project.comments(limit=1, offset=0))

```
However this is just returning empty brackets. (this is also the case no matter what the limit/offset is set to) 
Thanks!

**Comment by TimMcCool** [comment]
I just tested it with the project you gave and with another project that has 1 comment, and it worked for both. Sounds like an issue related to Scratch API caching.

**Comment by wvzackscratch** [comment]
Is there a way to clear the API cache? I also tried running this a few weeks ago and it did not work.

**Comment by TimMcCool** [comment]
> Is there a way to clear the API cache? I also tried running this a few weeks ago and it did not work.

On other API endpoints, I was able to do that by adding a random keyword argument. I'll make it so scratchattach automatically does that for all iterative API endpoints, to prevent API caching

**Comment by wvzackscratch** [comment]
Okay Thanks!

**Comment by TheCommCraft** [comment]
Or you could use a header to disable caching

Tim ***@***.***> schrieb am Fr., 25. Okt. 2024, 20:55:
