### ISSUE TITLE
ScratchHost account

### ISSUE THREAD

**Issue by Zocker-Welt** [TimMcCool/scratchattach#256]
how to verify a scratch host account

**Comment by TimMcCool** [comment]
You get a verification email (at least that's how it's supposed to work). I'll forward this issue to the owner of Scratch Host

**Comment by zacharyli2013** [comment]
The verification also doesn't work for me
![Screenshot 2024-10-29 184349](https://github.com/user-attachments/assets/b969e1d7-93fc-41da-872f-66396de62ad3)

**Comment by SpyC0der77** [comment]
you went to panel.justabock.online instead of panel.justablock.online

**Comment by SpyC0der77** [comment]
also, if scratchhost doesnt work, there is panel.sillydev.co.uk

**Comment by webbrowser11** [comment]
weird because that's where the EMAIL sends you!

**Comment by vgthecoder** [comment]
I don't even get the email.

**Comment by webbrowser11** [comment]
weird... did you use the right one?

**Comment by vgthecoder** [comment]
Yeah. I did.

**Comment by vgthecoder** [comment]
And no matter how hard I try, I cannot get it to "resend".

**Comment by webbrowser11** [comment]
you MUST have used the wrong email!

**Comment by vgthecoder** [comment]
I swear I didn't. I copied and pasted it. And triple checked.

**Comment by webbrowser11** [comment]
sometimes copy and pasting creates blank characters try again.

**Comment by vgthecoder** [comment]
I can assure you I typed it in correctly.

**Comment by webbrowser11** [comment]
okay

**Comment by webbrowser11** [comment]
btw what is the right way to do this: `    comments = session.get_comments(user, limit=2)`

**Comment by webbrowser11** [comment]
dude

**Comment by webbrowser11** [comment]
i need an answer SOON

**Comment by webbrowser11** [comment]
@vgthecoder

**Comment by webbrowser11** [comment]
i mean, this does not work at all!
```
import scratchattach as sa
from datetime import datetime

session = sa.login("sped_ai", "password")

project = session.connect_project("1090940082")

keyword = "/comment"

today = datetime.today().date()

def check_and_reply():
    comments = project.comments()

    today_comments = [
        comment for comment in comments 
        if datetime.fromtimestamp(comment['timestamp']).date() == today
    ]


    for comment in today_comments:
        if keyword in comment["content"]:
            comment_id = comment["id"]
            content = comment["content"]

            modified_content = comment.replace(keyword, " ",)

            project.reply_comment(comment_id, modified_content)
            print("replied.")

check_and_reply()
```

**Comment by TimMcCool** [comment]
> btw what is the right way to do this: ` comments = session.get_comments(user, limit=2)`

the right way is
```py
user = session.connect_user("username")
comments = user.comments(limit=2)
```

how is your code not working? do you get any errors?

**Comment by TheCommCraft** [comment]
Try resending the email now, I changed the mail settings

Tim ***@***.***> schrieb am Mo., 4. Nov. 2024, 09:55:

**Comment by vgthecoder** [comment]
To get it to resend the email, I just change the email. Am I doing that right? Or is there a hidden button somewhere in the UI?

**Comment by TimMcCool** [comment]
> i mean, this does not work at all!
> 
> ```
> 
> def check_and_reply():
> 
>     comments = project.comments()
> 
> ```

btw, the comments returned by this are sa.Comment objects in v2.0 and not dictionaries. This means you gotta use comment.content, comment.timestamp etc. to access this info

**Comment by TheCommCraft** [comment]
Yes, just change the mail to the same thing i think

vgthecoder ***@***.***> schrieb am Mo., 4. Nov. 2024, 15:25:

**Comment by TheCommCraft** [comment]
Are you sure you used the correct mail address

vgthecoder ***@***.***> schrieb am Mo., 4. Nov. 2024, 17:36:

**Comment by webbrowser11** [comment]
@TimMcCool im finding another way to do it using a listener.

**Comment by webbrowser11** [comment]
```
def SearchForNewComments():
    @events.event #Called when the event listener is ready
    def on_ready():
       print("Event listener ready!")
    @events.event
    def on_message(message):
        print(message.actor_username, "performed action", self.type)
        comments.append(message.content)
    events.start()
```

**Comment by webbrowser11** [comment]
idk if this is correct if you need the rest of the code i can give it to you

**Comment by webbrowser11** [comment]
comments is a list `        comments.append`

**Comment by webbrowser11** [comment]
source: https://github.com/webbrowser11/comment-bot/blob/main/bot.py

**Comment by TimMcCool** [comment]
you didn't define events anythere

you need to add something like 
```py
events = session.connect_message_events()
```
to your code

**Comment by TheCommCraft** [comment]
Have you looked inside your spam folder?

vgthecoder ***@***.***> schrieb am Mo., 4. Nov. 2024, 17:36:

**Comment by webbrowser11** [comment]
@TimMcCool should i connect it to a project?
`events = session.connect_message_events()`

**Comment by vgthecoder** [comment]
@TheCommCraft I have.

**Comment by TheCommCraft** [comment]
Then maybe just create a new account. It's working for me and I don't know
what the problem could be

vgthecoder ***@***.***> schrieb am Mi., 6. Nov. 2024, 18:09:

**Comment by vgthecoder** [comment]
@TheCommCraft I will loose my 2.5k of server hardware, but I'll try it.

**Comment by TheCommCraft** [comment]
I could give back to you, just give me your old and your new username

vgthecoder ***@***.***> schrieb am Mi., 6. Nov. 2024, 18:57:

**Comment by vgthecoder** [comment]
Okay. Still no email though.

**Comment by TheCommCraft** [comment]
username?

vgthecoder ***@***.***> schrieb am Mi., 6. Nov. 2024, 19:05:

**Comment by TheCommCraft** [comment]
also, could you send me a mail using the email adress to ***@***.***?
That way I know the mail belongs to you and maybe i can manually activate
your account

Simon Gilde ***@***.***> schrieb am Mi., 6. Nov. 2024, 19:28:

**Comment by vgthecoder** [comment]
@TheCommCraft ***@***.*** is not a valid email. Username is vg_coder.

**Comment by TheCommCraft** [comment]
the mail address is ```
tcc@thecommcraft.de
```

**Comment by TheCommCraft** [comment]
I need the old username and the new one

**Comment by vgthecoder** [comment]
Well I can assure you my email works fine. I sent a message yesterday and can receive messages from other services.

**Comment by TheCommCraft** [comment]
Just send a mail so I can verify that the mail is yours

vgthecoder ***@***.***> schrieb am Do., 7. Nov. 2024, 04:28:

**Comment by vgthecoder** [comment]
Perfect. panel.justablock.online Does not exist anymore.
