### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by DNin01** [TimMcCool/scratchattach#26]
May I suggest that you add a license file to your repository? This determines what copyright license your work is using/licensed under and is what gives users permissions to work with (modify, share, use) the software. This will make collaboration easier and make it more clear what others can do with the software.

Just pointing that out in case this is an oversight.

I'd recommend checking out [choosealicense.com](https://choosealicense.com/) to guide you on which license to use.

Thanks!

**Comment by TimMcCool** [comment]
Good idea, I'll do that later

**Comment by TimMcCool** [comment]
License added

**Comment by DNin01** [comment]
You might also want to do this on the PyPi version.
