### ISSUE TITLE
on_ready() event gets called twice

### ISSUE THREAD

**Issue by KR0K0BIL** [TimMcCool/scratchattach#261]
The on_ready event gets called in the BaseEventHandler start function:
https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/eventhandlers/_base.py#L27

It also gets called in every _updater function:
https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/eventhandlers/cloud_events.py#L33
https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/eventhandlers/cloud_events.py#L89
https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/eventhandlers/message_events.py#L23

**Comment by vgthecoder** [comment]
This is a problem I have, it prints "ready" twice which is annoying.

**Comment by TimMcCool** [comment]
will be fixed

**Comment by TimMcCool** [comment]
fixed in v2.1.4

**Comment by vgthecoder** [comment]
Thank You!
