### ISSUE TITLE
CloudLogEvents _updater doesn't work

### ISSUE THREAD

**Issue by KR0K0BIL** [TimMcCool/scratchattach#262]
This code goes through the logs backwards, from old to new. `self.last_timestamp` is the timestamp of the newest log, so `_a.timestamp` (the oldest log) is always less than `self.last_timestamp` and the loop stops.
https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/eventhandlers/cloud_events.py#L96-L100
It should be like this:
`if _a.timestamp <= self.last_timestamp: continue`

**Comment by TimMcCool** [comment]
will be fixed asap
