### ISSUE TITLE
ProjectBody Block json optional parameters

### ISSUE THREAD

**Issue by KR0K0BIL** [TimMcCool/scratchattach#263]
I've made a python program that minimizes the size of the project.json file. This includes removing unnecessary block parameters like parent, inputs, fields, shadow, topLevel and next to reduce the file size from 4.9 MB to 3.7 MB. The code below makes missing parameters possible (except opcode). I've also added descriptions for all parameters.

    def from_json(self, data: dict):
            self.opcode = data["opcode"] # The name of the block
            self.next_id = data.get("next", None) # The id of the block attached below this block
            self.parent_id = data.get("parent", None) # The id of the block that this block is attached to
            self.input_data = data.get("inputs", None) # The blocks inside of the block (if the block is a loop or an if clause for example)
            self.fields = data.get("fields", None) # The values inside the block's inputs
            self.shadow = data.get("shadow", False) # Whether the block is displayed with a shadow
            self.topLevel = data.get("topLevel", False) # Whether the block has no parent
            self.mutation = data.get("mutation", None) # For custom blocks
            self.x = data.get("x", None) # x position if topLevel
            self.y = data.get("y", None) # y position if topLevel
            
        def to_json(self):
            output = {"opcode":self.opcode,"next":self.next_id,"parent":self.parent_id,"inputs":self.input_data,"fields":self.fields,"shadow":self.shadow,"topLevel":self.topLevel,"mutation":self.mutation,"x":self.x,"y":self.y}
            return {k: v for k, v in output.items() if v}

https://github.com/TimMcCool/scratchattach/blob/b5d6321140ea1404c8e8068895d7e7aba3042672/scratchattach/other/project_json_capabilities.py#L52-L68

**Comment by TimMcCool** [comment]
Nice! I'll implement that. Btw you're free to open a pull reuqest to contribute your code
