### ISSUE TITLE
commands dont match

### ISSUE THREAD

**Issue by webbrowser11** [TimMcCool/scratchattach#264]
docs:
![Screenshot 2024-11-01 120902](https://github.com/user-attachments/assets/b77309e9-bbd7-4acb-a850-fb3d2385d4d4)
website:
![Screenshot 2024-11-01 121122](https://github.com/user-attachments/assets/b4eac4cd-fa20-4034-98fa-013bbfa49fe9)

**Comment by TheCommCraft** [comment]
both work sometimes

**Comment by webbrowser11** [comment]
oh.
