### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'connect_scratch_cloud'

### ISSUE THREAD

**Issue by webbrowser11** [TimMcCool/scratchattach#265]
Traceback (most recent call last):
  File "c:\Users\(username)\Downloads\SAuth.py", line 22, in <module>
    cloud = session.connect_scratch_cloud("1090320725") # Connect to Scratch's cloud
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'connect_scratch_cloud'. Did you mean: 'connect_tw_cloud'?]

this was correct in the docs, but not in my code.

**Comment by webbrowser11** [comment]
i need to finish this soon so, i need an answer soon

**Comment by webbrowser11** [comment]
here is another question:
events = cloud.events()
@events.event
def on_set(activity): #Called when a cloud var is set
    activity.load_log_data()

def Sector2(activity): # can i call outside of this strip (example: under this strip of code)?
    if activity.username == username:
        GenerateKey
        print(f"Please eneter this key into the input prompt on the project: {Key} ")

events.start()

**Comment by webbrowser11** [comment]
if someone could look over the code i got now that'd be great

**Comment by TheCommCraft** [comment]
update your scratchattach

T_cat9000_2 ***@***.***> schrieb am Sa., 2. Nov. 2024, 00:21:

**Comment by webbrowser11** [comment]
okay how

**Comment by TimMcCool** [comment]
Run
```py
pip install -U scratchattach
```
in your command prompt to update scratchattach

If you can't update it for whatever reason, use `session.connect_cloud("project_id")` instead

**Comment by webbrowser11** [comment]
Alright that's solved and i might be dumb because idk what is happening here (am i missing something?): 

```
# first auth section
events = cloud.events()
def on_set(activity): #Called when a cloud var is set
    activity.load_log_data()\

def Sector2(activity):
    if activity.username == username:
        GenerateKey()
        input(f"Please eneter this key into the input prompt on the project: {Key} ")

def Sector1(activity):
    input("Get on scratch and go to the project: https://scratch.mit.edu/projects/1090320725/")
    print("MAKE SURE TO KEEP THE PROJECT WINDOW OPEN")
    if activity.username == username:
        activity.username = None
        Sector2()
Sector1()
events.start()
```
error:
```
Traceback (most recent call last):
  File "c:\Users\Graham\Downloads\SAuth.py", line 45, in <module>
    Sector1()
TypeError: Sector1() missing 1 required positional argument: 'activity'
```

**Comment by TheCommCraft** [comment]
You need to call Sector1 and Sector2 in on_set with the argument activity

T_cat9000_2 ***@***.***> schrieb am Sa., 2. Nov. 2024, 01:05:

**Comment by SpyC0der77** [comment]
it is connect_cloud not connect_scratch_cloud

**Comment by SpyC0der77** [comment]
I saw this 11 minutes after it was posted but couldn't login cuz i was on a diff computer

**Comment by SpyC0der77** [comment]
quick question tim, in your button detector, there is a really cool icon animation thing in the middle that changes if you touch the buttons. Could you perhaps make that a standalone project people could use?

**Comment by webbrowser11** [comment]
my code looks like this now:
```
import scratchattach as sa
import sys
import random
import time

print("Keep this window open while executing the project bits")

# get the scratch login
def GetScratchLogin():
    global username
    global password
    username = input("Scratch username: ")
    password = input("Scratch password: ")

def GenerateKey():
    global Key
    Key = f"{Key}{random.randint(0, 9)}"

# login to scratch
GetScratchLogin()
session = sa.login(username, password)
cloud = session. connect_cloud("1090320725") # Connect to Scratch's cloud

if session.new_scratcher == True:
    print("You can not use this auth engine as you are a new scratcher")
    time.sleep(3)
    sys.exit()

# first auth section
events = cloud.events()
def on_set(activity): #Called when a cloud var is set
    activity.load_log_data()
    Sector1()

def Sector2(activity):
    if activity.username == username:
        GenerateKey()
        input(f"Please eneter this key into the input prompt on the project: {Key} ")

def Sector1(activity):
    input("Get on scratch and go to the project: https://scratch.mit.edu/projects/1090320725/")
    print("MAKE SURE TO KEEP THE PROJECT WINDOW OPEN")
    if activity.username == username:
        activity.username = None
        Sector2()
Sector1()
events.start()
```

**Comment by webbrowser11** [comment]
and i got the same error

**Comment by SpyC0der77** [comment]
scratchauth

**Comment by SpyC0der77** [comment]
https://auth.itinerary.eu.org/

**Comment by webbrowser11** [comment]
im trying to build my own.

**Comment by SpyC0der77** [comment]
ok

**Comment by webbrowser11** [comment]
yeah anyways sectoe1() is supposed to be called before sector2()

**Comment by SpyC0der77** [comment]
user = session.connect_linked_user() # Returns a sa.User object

verificator = user.verify_identity(verification_project_id=1090560162) # The project id where the user has to comment can be specified as `verification_project_id` keyword argument 
print(verificator.code)
while True:
    print(verificator.check())
    if(verificator.check() == True):
        print("Verification successful!")
        break
    time.sleep(1) this worked for me

**Comment by webbrowser11** [comment]
oh

**Comment by TimMcCool** [comment]
@webbrowser11 Your code doesn't work because the attributes of the `activity` object are not updated when a new cloud activity is detected. Instead, the on_set function is called another time with a new `activity` object (representing the new cloud activity).

As SpyC0der77 said, scratchattach has a built-in engine for verifying a user's identity, so I'd suggest using that one instead.

**Comment by TheCommCraft** [comment]
you don't need to replace connect_scratch_cloud, just update by writing pip
install --upgrade scratchattach in your console

Tim ***@***.***> schrieb am Sa., 2. Nov. 2024, 18:58:

**Comment by webbrowser11** [comment]
i did @TheCommCraft but instead of fixing anything i cleaned up @SpyC0der77 's code then used it (with my project ofc).
get code here:

run here:
https://scratch.mit.edu/projects/1090320725/

**Comment by SpyC0der77** [comment]
that looks a lot like chatgpt code...

**Comment by SpyC0der77** [comment]
also add @cartercypherout3 in the credits

**Comment by webbrowser11** [comment]
> that looks a lot like chatgpt code...

well i did use him to fix it up and then i REWROTE NOT copied the code into my python file
