### ISSUE TITLE
Can't remix an unshared project

### ISSUE THREAD

**Issue by SpyC0der77** [TimMcCool/scratchattach#270]
I can't remix an unshared project (PartialProject class) even though it says I can in the docs

**Comment by TimMcCool** [comment]
have you updated scratchattach to v2.0?

what error(s) are you getting?

are you sure the project id used to connect the unshared project is valid?

The method for remixing an unshared project is
```py
project = partial_project.create_remix()
```
Back when I tested it, it worked

**Comment by SpyC0der77** [comment]
import scratchattach as sa
import json

session = sa.login_by_id(my login)
user = session.connect_linked_user()
project = sa.get_project(1090564580)

project.create_remix()
Warning: For methods that require authentication, use
session.connect_project instead of get_project
Traceback (most recent call last):
  File "C:\Users\Carter\Code\Python\ScratchAttach\lol.py", line 8, in
<module>
    project.create_remix()
  File
"C:\Users\Carter\Code\Python\ScratchAttach\.venv\Lib\site-packages\scratchattach\site\project.py",
line 128, in create_remix
    self._assert_auth()
  File
"C:\Users\Carter\Code\Python\ScratchAttach\.venv\Lib\site-packages\scratchattach\site\_base.py",
line 37, in _assert_auth
    raise exceptions.Unauthenticated(
scratchattach.utils.exceptions.Unauthenticated: No login / session
connected.

The object on which the method was called was created using
scratchattach.get_xyz()
Use session.connect_xyz() instead (xyz is a placeholder for user / project
/ cloud / ...).

More information:
https://scratchattach.readthedocs.io/en/latest/scratchattach.html#scratchattach.utils.exceptions.Unauthenticated
also check out @ScratchAttachDemo on scratch :) I set it up

**Comment by TimMcCool** [comment]
You need to use `session.connect_project(1090564580)` instead of `sa.get_project(1090564580)`

It also says that in the error message

**Comment by webbrowser11** [comment]
yeah i wish i could use scratchattach better :(

**Comment by SpyC0der77** [comment]
> You need to use `session.connect_project(1090564580)` instead of `sa.get_project(1090564580)`
> 
> It also says that in the error message
> 
> I saw @ScratchAttachDemo :) nice projects

thanks man
