### ISSUE TITLE
does_exist function uses wrong requests 'module'

### ISSUE THREAD

**Issue by FAReTek1** [TimMcCool/scratchattach#274]
In the ```user.User.does_exist()``` method, the 'requests module' is used. However, this is actually using the requests wrapper which handles status codes such as 404 or 429.
![image](https://github.com/user-attachments/assets/539213f1-8c2c-4cfa-8cc9-ba2c4e1f1d5f)

But if the status code is 404, then an error will have been raised anyway:
![image](https://github.com/user-attachments/assets/a5ca5847-59c4-4381-88d6-178109a19017)

So this code can't run. Instead, you may need to use a try except statement.

In addition, the code runs two GET requests, which is inefficient. You only need one.

Also, when receiving an  'Our server is scratching its head' page, the status code will be 200 to show the GUI, but the status is 404.

**Comment by TimMcCool** [comment]
it won't raise an error when the status code is 404 (check your screenshot again). But the two GET requests are indeed inefficient, this will be fixed in the next update

**Comment by FAReTek1** [comment]
hmm,when i was running code i was getting an error. i would have to chdckt hat, maybe i was getting a 403 or something
