### ISSUE TITLE
Filter bot doesn't work/フィルターボットが使えない

### ISSUE THREAD

**Issue by unajyuumoto-python-Js-html-css** [TimMcCool/scratchattach#288]
I probably shouldn't post this here, but the filter bot [from scratchattach import HardFilter, ...] doesn't work. Maybe updating it will fix it (was there an update in the first place?) Or maybe reinstalling it will fix it, but I don't know how to do that.

/

ここに書き込むべきではないかもしれませんが、フィルターボットを[from scratchattach import HardFilter, ...] が動作しません。もしかしたら、アップデートすれば直る（そもそもアップデートがあったのか？）または、再インストールすれば直るかもしれませんが、その方法がわかりません。

**Comment by kakeruzoku** [comment]
`[from scratchattach import HardFilter, ...] が動作しません。`

→コマンドプロンプトで`pip install -U scratchattach`を実行してアップデートしてみてください。

**Comment by unajyuumoto-python-Js-html-css** [comment]
Requirement already satisfied:
と出るだけで、scratchattachには関係なさそうなログしか出ません。
これはアップデート成功なのでしょうか？

**Comment by kakeruzoku** [comment]
[このコメント](https://github.com/TimMcCool/scratchattach/issues/288#issuecomment-2481196690 )への返信
> Requirement already satisfied: と出るだけで、scratchattachには関係なさそうなログしか出ません。 これはアップデート成功なのでしょうか？

`Requirement already satisfied:`とでているなら最新版になっているはずです。

それでも失敗する場合は
重要な情報(パスワード等)を抜いたコードと発生するエラーを教えてください。

コードの一例:
```python
import scratchattach as s3

#ログイン・フィルタークラス作成
session = s3.login("username", "password")
filterbot = session.connect_filterbot(log_deletions=True)

#フィルターを追加
filterbot.add_filter(
    s3.HardFilter("宣伝ブロック", contains="https://scratch.mit.edu/projects/")
)

filterbot.add_filter(
    s3.SpamFilter("スパムブロック")
)

#実行
filterbot.start()
```

**Comment by unajyuumoto-python-Js-html-css** [comment]
うまくいきました！ありがとうございました。2024/11/18 14:42 かける族 ***@***.***>:
このコメントへの返信

Requirement already satisfied: と出るだけで、scratchattachには関係なさそうなログしか出ません。 これはアップデート成功なのでしょうか？

Requirement already satisfied:とでているなら最新版になっているはずです。
それでも失敗する場合は
重要な情報(パスワード等)を抜いたコードと発生するエラーを教えてください。
コードの一例:
import scratchattach as s3

#ログイン・フィルタークラス作成
session = s3.login("username", "password")
filterbot = session.connect_filterbot(log_deletions=True)

#フィルターを追加
filterbot.add_filter(
    s3.HardFilter("宣伝ブロック", contains="https://scratch.mit.edu/projects/")
)

filterbot.add_filter(
    s3.SpamFilter("スパムブロック")
)

#実行
filterbot.start()
