### ISSUE TITLE
Incorrect info on wiki/documentation ("Get your session id")

### ISSUE THREAD

**Issue by smiley-guyus** [TimMcCool/scratchattach#290]
## Here is a screenshot below, showing how to get the session id in safari;

<img width="1141" alt="dss" src="https://github.com/user-attachments/assets/aa53b0ba-1396-4e54-9d53-edc7958925e9">

**Comment by TheCommCraft** [comment]
and the same as in chrome

**Comment by TheCommCraft** [comment]
nevermind

**Comment by smiley-guyus** [comment]
@TimMcCool When will this be resolved?

**Comment by TimMcCool** [comment]
later today

**Comment by smiley-guyus** [comment]
> later today

@TimMcCool is been 3 days now, when is it going to get resolved? Is it hard to edit the wiki page or you just not had time? (if you didn't have time its ok)

**Comment by smiley-guyus** [comment]
> later today

@TimMcCool It has been 3 weeks?

**Comment by FAReTek1** [comment]
hes quite inactive because hes at university i think (my pr took like a month to be merged asw)

**Comment by FAReTek1** [comment]
i put the screenshot in the page. I don't use macos though so I can't confirm that the steps 1-5 from above apply as well

**Comment by smiley-guyus** [comment]
@FAReTek1 the keybind for inspect element on Mac is ⌘ + ⌥ + I and is Storage tab instead of Application

**Comment by smiley-guyus** [comment]
Users will need to [follow this step to enable the inspect element though.](https://developer.apple.com/documentation/safari-developer-tools/enabling-developer-features)

**Comment by FAReTek1** [comment]
ok, i'll add a note

**Comment by FAReTek1** [comment]
How is it now? @smiley-guyus

**Comment by smiley-guyus** [comment]
@FAReTek1 Looks good, ill close the issue now.
