### ISSUE TITLE
project_json_capabilites is very messy

### ISSUE THREAD

**Issue by FAReTek1** [TimMcCool/scratchattach#291]
I have had issues when I have been trying to edit the project_json_capabilites.py file due to the nature that it has been coded. PyCharm really dislikes the code because it is full of bad style coding: 
![image](https://github.com/user-attachments/assets/6d5eadea-0226-443f-ba81-d26037d203c9)
![image](https://github.com/user-attachments/assets/472c7396-b447-408a-aaa7-74f9831b5057)
37 warnings and 57 weak warnings!!!
![image](https://github.com/user-attachments/assets/ed59a57b-3cb9-4dd6-83c0-2a77031b822a)
overriding a builtin name!!
![image](https://github.com/user-attachments/assets/05bc54ad-32f3-461f-a1f0-843383bc96fa)
How is this readable?!?!?!?!?!?!? It's almost like a poem with its references that go to the left and right

Regardless of that, the methods are filled with 'potentially non-existent' attributes like `self.sprite` which are not defaulted to `None `, which makes code completion extremely unhelpful as these attributes are not listed, and it makes it very ugly as there are yellow underlines everywhere.

I have my own project json capabilites library called sbeditor and have a decent amount of experience with project json editing using scripts. the project_json_capabilites file is one I would really like to contribute to however these issues are making it really hard for me to edit. I may make a pr in response to this issue to address this

sorry if this seems like a rant

**Comment by FAReTek1** [comment]
i have now encountered severe fundamental issues in the system of sbeditor and will restart the project. i will probably integrate it directly into a branch of scratchattach in my own fork. if it becomes significantly more powerful than the current json capabilities, then i will open a pr

**Comment by TheCommCraft** [comment]
I would suggest you maybe take a look at custom json decoders

**Comment by FAReTek1** [comment]
wdym? can you send link

**Comment by TheCommCraft** [comment]
This might help: https://stackoverflow.com/questions/48991911/how-to-write-a-custom-json-decoder-for-a-complex-object
With that, you could have it be decoded directly into the needed classes

**Comment by FAReTek1** [comment]
ok. i think i might have an idea what to do

**Comment by FAReTek1** [comment]
i feel there may be issues with things like the lists which do not contain any identifying Information - the one that store numbers will be hard to differentiate from other lists. if youre unlucky, jt may be exactly equivalent to a scratch list. so afaik the to json and from json methods seem like an easier/potentailly cleaner way of programming it

**Comment by FAReTek1** [comment]
bad wordong but hmm

**Comment by FAReTek1** [comment]
i am now working on [a branch of scratchattach](https://github.com/FAReTek1/scratchattach/tree/sbeditor) to do this

**Comment by FAReTek1** [comment]
see `scratchattach/editor`

**Comment by FAReTek1** [comment]
Parsing sb3 is now complete. Now we need exporting. Then editing, then come 'plugins'

**Comment by FAReTek1** [comment]
theyre not really plugins, just idk what to call them. ill talk about them more when i get to that point in development

**Comment by SpyC0der77** [comment]
So, in summary, you are making a python scratch project editor

**Comment by FAReTek1** [comment]
sbedutir v2
