### ISSUE TITLE
scratchattach allows to hack accounts, spam profile and projects

### ISSUE THREAD

**Issue by WWX-Team** [TimMcCool/scratchattach#293]
Hi, I wanna make a report here as a group of scratchers called "Scratch Elites" uses scratchattach to violate the site's rules.

## Hacking students accounts

I first want to leave a reminder : student accounts, when created, use a PIN (6-number) password generated by the website and communicated to the class owner, who next gives this PIN to the student.
So it's very easy to crack with a small code students account - please consider add a delay while sending wrong session profile

## Spam

scratchattach allows to spam comments - during the past few weeks, several profile comment sections have been closed due to abuse of the module. I suggest you also add a delay, in addition to a simple duplicate content checker.

Have a good day, report sent for [latribunescratch](https://scratch.mit.edu/users/latribunescratch/)

**Comment by TheCommCraft** [comment]
The scratch API allows for this

**Comment by TheCommCraft** [comment]
The scratch API allows for this

**Comment by TheCommCraft** [comment]
Also, who is this Scratch Elite supposed to be?

**Comment by smiley-guyus** [comment]
Someone could just fork the library and remove the delays if delays are added, so it wouldnt be of any benefit to add that.

**Comment by FAReTek1** [comment]
just report them. if an update to add delays is added it will:
- be annoying for most users
- be very tedious to implement 
- be useless because you can just fork an old version of the library ( or edit the code locally - this can be done to bypass the project creation speed)

**Comment by TimMcCool** [comment]
As FAReTek1 said, hackers could do this kind of stuff even before scratchattach existed, and even if restrictions were added to scratchers, hackers could still do it. However, restrictions would harm honest developers who are using scratchattach to build innovative projects.
