### ISSUE TITLE
activity.username returning None

### ISSUE THREAD

**Issue by Fox595676** [TimMcCool/scratchattach#297]
Heya! Today I've been working on checking if a user has set a variable, rather than the script.

But it seems to just return None, whether the user or the script set the variable.

Here's a simplified example:

```python
import scratchattach as sa

id = "<id>"
user = "<username>"
project = "<projectid>"

session = sa.login_by_id(id, username=user)
cloud = session.connect_cloud(project)
events = cloud.events()

@events.event
def on_set(activity):
    test = activity.username, activity.user
    print(test)
events.start()
```

And here's the output, no matter who sets it:
```python
(None, None)
```

Have I done something wrong, or is this broken?

**Comment by kakeruzoku** [comment]
During normal events, usernames are not collected. (This is due to Scratch specifications.)

If you want to access your username frequently, Use cloudlogevent.

`events = cloud.events(use_logs=True)`

**Comment by Fox595676** [comment]
Thank you so much for the quick reply <3
I'll adjust my script accordingly!

**Comment by SpyC0der77** [comment]
What are you making?

**Comment by Fox595676** [comment]
> What are you making?

https://github.com/Fox595676/scratch2bash

As the name aptly suggests, this is Bash in Scratch!

**Comment by TheCommCraft** [comment]
Maybe this should be added to the docs

Fox Woodbury ***@***.***> schrieb am Sa., 14. Dez. 2024,
02:56:
