### ISSUE TITLE
IDEA: Detect if replit is being used, and use a proxy if so.

### ISSUE THREAD

**Issue by UniqueName12345** [TimMcCool/scratchattach#30]
Basically what the title above says. I know that you can just use session id login, but that's a lot heftier of a process than a username and password.

- [ ] Find a way to check for replit
- [ ] Implement the way
- [ ] Use a proxy for replit users
- [ ] Check the proxy works
- [ ] Confirm replit integration works

**Comment by TimMcCool** [comment]
Interesting idea, I'll consider implementing that

**Comment by TimMcCool** [comment]
Update: I won't implement a proxy (I don't have time), but if someone else wants to do that they can create a pull request.

**Comment by UniqueName12345** [comment]
> Update: I won't implement a proxy (I don't have time), but if someone else wants to do that they can create a pull request.

Thanks.
