### ISSUE TITLE
More hosting options.

### ISSUE THREAD

**Issue by DagriffpatchfanHosting** [TimMcCool/scratchattach#301]
https://botcore.org/
https://www.pella.app
https://www.hidencloud.com/
https://bot-hosting.net/
https://skycastle.us/

The following all offer hosting for discord bots, which as I found out, is great for hosting scratchattach scripts. It only took me a few hours of googling to find them ;)

**Comment by FAReTek1** [comment]
personally i use fly.io because it works ok asw. maybe ill look into those

**Comment by DagriffpatchfanHosting** [comment]
> personally i use https://fly.io because it works ok asw. maybe ill look into those

But it requires a credit card :( No way my parents would let me use theirs on some random website

**Comment by FAReTek1** [comment]
ot wont charge unless you use the computing power over a certain amount. but yes

**Comment by DagriffpatchfanHosting** [comment]
> ot wont charge unless you use the computing power over a certain amount. but yes

Do you think TimMcCool will add them? The only downside is that they require you to earn coins (by watching ads or referring others) or hit renew every couple of days in order to keep your servers running.

**Comment by FAReTek1** [comment]
similar to how scrwtchhost worked/wae going to work so maybe

**Comment by TimMcCool** [comment]
will be added to the docs
