### ISSUE TITLE
Remove pella.app from the more hosting options. 

### ISSUE THREAD

**Issue by DagriffpatchfanHosting** [TimMcCool/scratchattach#313]
It contains links to a gambling site. Can you please add:
https://dash.huguitisnodes.host/register
And:
https://sillydev.co.uk/

**Comment by FAReTek1** [comment]
where are there links, may i ask

**Comment by TheCommCraft** [comment]
probably ads

**Comment by DagriffpatchfanHosting** [comment]
> where are there a link to a gambling website, may i ask?

They have five or something ads you can click to renew your server and one of them is a link to a gambling site.

**Comment by TheCommCraft** [comment]
Should I also add `panel.chilldev.xyz`?

**Comment by SpyC0der77** [comment]
@TheCommCraft how do you find jexactyl implementations?

**Comment by DagriffpatchfanHosting** [comment]
> panel.chilldev.xyz

From what I can see, it’s a pay only service…the other ones linked, you pay for them by watching ads.

**Comment by DagriffpatchfanHosting** [comment]
> @TheCommCraft how do you find jexactyl implementations?

If you look up free 24/7 discord bot hosting and then open up like 20 tabs looking for services which are actually free

**Comment by DagriffpatchfanHosting** [comment]
> probably ads

Can you please remove pella.app ?

**Comment by TheCommCraft** [comment]
ok

DagriffpatchfanHosting ***@***.***> schrieb am Mo., 30. Dez.
2024, 22:24:

**Comment by DagriffpatchfanHosting** [comment]
Was that a yes for the video?

**Comment by TheCommCraft** [comment]
Maybe for the video you should ask Tim

**Comment by DagriffpatchfanHosting** [comment]
> Maybe for the video you should ask Tim

Ok

**Comment by TimMcCool** [comment]
> Was that a yes for the video?

If it's good I'll add it
