### ISSUE TITLE
 'NoneType' object has no attribute '_username'

### ISSUE THREAD

**Issue by blockitjimjam** [TimMcCool/scratchattach#35]
File "c:\Users\scrat\Desktop\ahahahh.py", line 8, in <module>
    project.love()
  File "C:\Users\scrat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scratchattach\_project.py", line 216, in love
    f"https://api.scratch.mit.edu/proxy/projects/{self.id}/loves/user/{self._session._username}",
AttributeError: 'NoneType' object has no attribute '_username'

this is the code:
 projectnum = randint(0,600000000)
 project = scratch3.get_project(f"{projectnum}")
 project.love()

**Comment by blockitjimjam** [comment]
now, the project is accessible, I've used try and except to make sure of that.

**Comment by preface-egeriekung** [comment]
Did you have this warning?
`Warning: Logged in, but couldn't fetch XToken. Cloud variables will still work, but other features may not work properly.`

**Comment by TimMcCool** [comment]
You can't use the love() function if the project object was created with `scratch3.get_project("projectid")`. Please use 
```
session = scratch3.login("username", "password")
project = session.connect_project("projectid")
project.love()
```
instead
