### ISSUE TITLE
Scratchattach hanging on conn.get_var("hi").

### ISSUE THREAD

**Issue by BenPI88** [TimMcCool/scratchattach#38]
Any Fixes?

**Comment by jimjamgithub** [comment]
and the variable name is correct?

**Comment by BenPI88** [comment]
> and the variable name correct?

Yes.

**Comment by TimMcCool** [comment]
Interesting. Maybe try using scratch3.get_var("project_id", "variable_name") instead. This function does the same, but it tries to get the value from the clouddata logos

**Comment by TimMcCool** [comment]
This doesn't look like a bug. Try using scratch3.get_var("project_id", "variable_name") if conn.get_var isn't working for you

**Comment by TimMcCool** [comment]
Turned out this may actually be a bug that occurs then getting a turbowarp cloud variable. I'll look into it.

**Comment by TimMcCool** [comment]
The issue is caused by turbowarp's updated cloud variable guidelines. Will be fixed soon.

**Comment by TimMcCool** [comment]
Scratchattach is only hanging on conn.get_var if the variable doesn't exist. This issue will be fixed.
