### ISSUE TITLE
Question to TimMcCool (and possibly other contributors)

### ISSUE THREAD

**Issue by penlight-x** [TimMcCool/scratchattach#42]
Do I have permission to rewrite this library in C++ (maybe with a little bit of modifications for my own taste, but mostly the same methods and code) and release it to the public?

**Comment by penlight-x** [comment]
This is because I need really fast code and Python is pretty slow.

**Comment by TimMcCool** [comment]
Yes, you have permission if you credit the original library. But I don't think the C rewrite will be faster in a way that makes a difference
