### ISSUE TITLE
Forgot "project.title"

### ISSUE THREAD

**Issue by mas6y6** [TimMcCool/scratchattach#43]
Hey Tim You Forgot the "project.title" function in the projects area

Attributes:

project.id  #Returns the project id
project.url  #Returns the project url

project.title #Returns the project title<<<<<<< This is that you forgot

project.author  #Returns the username of the author
project.comments_allowed  #Returns True if comments are enabled
project.instructions
project.notes  #Returns the 'Notes and Credits' section
project.created  #Returns the date of the project creation
project.last_modified  #Returns the date when the project was modified the last time
project.share_date
project.thumbnail_url
project.remix_parent
project.remix_root
project.loves  #Returns the love count
project.favorites #Returns the project's favorite count
project.remix_count  #Returns the number of remixes
project.views  #Returns the view count
project.project_token
# ----- ----- #
project.update()  #Updates the above data

**Comment by TimMcCool** [comment]
Thanks, is fixed now
