### ISSUE TITLE
Updated TurboWarp cloud variable guidelines

### ISSUE THREAD

**Issue by GarboMuffin** [TimMcCool/scratchattach#44]
Hello, I have put some updated guidelines for TurboWarp cloud variable bot developers over here: https://docs.turbowarp.org/cloud-variables#advanced

Most notably we would like cloud variable libraries and bots to each be setting a unique `User-Agent` header. I don't know enough about this project to know how many of those guidelines will affect you.

**Comment by TimMcCool** [comment]
Thanks for the info. This explains issue #38 38

**Comment by GarboMuffin** [comment]
What User-Agent does scratchattach use when connecting to clouddata.turbowarp.org?

Note that I am very likely to start blocking *all* connections that do not provide a user agent, because there are just too many of those

**Comment by GarboMuffin** [comment]
FYI the User-Agent requirements are now being enforced. You have had more than sufficient notice to get users to start identifying themselves properly.

Also, please stop exposing APIs like this:

https://github.com/TimMcCool/scratchattach/blob/c395b6a400ebf60cc20c8596bf2d6f0465147a35/scratchattach/cloud.py#L439-L467

People will use that in a while True instead of just opening one connection and listening for updates. That causes significant load for us.

**Comment by Sussy-OS** [comment]
I couldn't find anywhere in the wiki how to set a user agent. I just started programming a turbowarp server today, and found it to not function. Is scratchattach not identifying a user agent still?

**Comment by GarboMuffin** [comment]
@TimMcCool How do people set user-agent in this library as needed by https://docs.turbowarp.org/cloud-variables#user-agent ?

**Comment by TimMcCool** [comment]
Unfortunately the library used by scratchattach (websocket-client) doesn't offer a built-in way to specify the user agent during websocket connection. I'll find a solution for that and update the library until next week.

> Also, please stop exposing APIs like this:
@GarboMuffin There's a warning in the documentation that tells users to not spam the function.
> At least detect if its being called more then a couple times per minute and throw a warning.
I'll add that

**Comment by GarboMuffin** [comment]
https://websocket-client.readthedocs.io/en/latest/examples.html#setting-custom-header-values

**Comment by TimMcCool** [comment]
> https://websocket-client.readthedocs.io/en/latest/examples.html#setting-custom-header-values

Oh, okay. Thanks.
