### ISSUE TITLE
Number of arguments is 1 above needed

### ISSUE THREAD

**Issue by OniLang-1123t** [TimMcCool/scratchattach#45]
session = scratch.Session(my_secret, "MadAsTK")
TypeError: __init__() takes 2 positional arguments but 3 were given

I'm using replit, so my_secret is my session btw
I tried this with VS Code and got the same error

**Comment by TimMcCool** [comment]
the correct code is
```py
session = scratch.Session(my_secret, username="MadAsTK")
```

Does this fix the error?
