### ISSUE TITLE
AttributeError: 'User' object has no attribute 'about_me'

### ISSUE THREAD

**Issue by WordReaper** [TimMcCool/scratchattach#49]
Basically I'm making a statistics project. I manually scraped 96,000 Scratch users. I'm trying to save all their data to a text file. But this function sometimes doesn't work, and says the error in the title.
`def get_user_data(obj: scratch3.User):
    return str({"username": obj.username, "joinDate": obj.join_date, "aboutMe": obj.about_me, "workingOn": obj.wiwo, "followers": obj.follower_count(), "following": obj.following_count(), "projects": obj.project_count(), "favorites": obj.favorites_count(), "studios": obj.studio_count(), "usersFollowing": obj.following()})`

**Comment by WordReaper** [comment]
oh, I didn't manually scrape them, I used a program to extract them from griffpatch's followers

**Comment by TimMcCool** [comment]
Appears to a be a scratchattach bug. I just fixed it, update scratchattach with pip install -U scratchattach
