### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by DragonsRule2000** [TimMcCool/scratchattach#5]
When using pip install scratchattach I get an error message saying "'pip' is not recognized as an internal or external command,
operable program or batch file." This is for using command prompt, shell, and python. 

Please reply here, or if urgent at tjkorbel7@outlook.com  OR xkorbt@baystudent.org.

(This issue was also put on Tims scratch page.)

**Comment by TimMcCool** [comment]
This is a common problem: https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/

**Comment by DragonsRule2000** [comment]
> This is a common problem: https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/

Okay thank you
