### ISSUE TITLE
Not setting cloud variables.

### ISSUE THREAD

**Issue by hashtag-source** [TimMcCool/scratchattach#53]
My script runs fine and everything seems normal but it does not actually update the variable when looking at the logs. I have tried this on multiple different computers with different scratch acounts.
`import scratchattach as scratch3`
`session = scratch3.login("username", "password")`
`conn = session.connect_cloud("projectid")`
`conn.set_var("variable", "value")`
`conn.disconnect()`
I know scratch has been changing how their api works so idk if thats affecting it. I can still pull values though.

**Comment by Ellirio2** [comment]
Id suggest using the sessionID and username instead cus that works for me in Replit

**Comment by hashtag-source** [comment]
ok ill try that

**Comment by hashtag-source** [comment]
still not working

**Comment by hashtag-source** [comment]
here is the project but its the same on any project I've tried.
https://scratch.mit.edu/cloudmonitor/759236467/

**Comment by Ellirio2** [comment]
have you run pip install - U scratchattach in shell then 
`import scratchattach as scratch3

session = scratch3.login("yoursessionID", "password")

conn = session.connect_cloud("projectid")

conn.set_var("variable", "value") 
`

**Comment by Ellirio2** [comment]
replace  yoursessionID with your session ID if you know what that is btw  are you in Replit?

**Comment by hashtag-source** [comment]
no im in power shell and i tried session id

**Comment by hashtag-source** [comment]
Also I have scratch attach installed. Are you sure its working for you right now?

**Comment by Ellirio2** [comment]
it should work fine is there a error?
or what

**Comment by hashtag-source** [comment]
I dont get any errors.

**Comment by Ellirio2** [comment]
uhuh do you have a replit account?

**Comment by hashtag-source** [comment]
No should i get one?

**Comment by Ellirio2** [comment]
Yuh

**Comment by hashtag-source** [comment]
ok i did

**Comment by Ellirio2** [comment]
I'll can help you on there then :D

**Comment by hashtag-source** [comment]
ok what info do you need?

**Comment by Ellirio2** [comment]
Tell me when your online tomorrow I'll help you!

**Comment by hashtag-source** [comment]
ok thanks

**Comment by hashtag-source** [comment]
cannot get Xtoken

**Comment by hashtag-source** [comment]
maybe its my scratch account because when i go to cloud data for other projects they all say around 10 hours ago.

**Comment by hashtag-source** [comment]
Scratch is having cloud variable bugs right now.

**Comment by TimMcCool** [comment]
Scratch's cloud variables are broken atm: https://scratch.mit.edu/discuss/topic/646279

**Comment by Ellirio2** [comment]
btw way if you put data_from_websocket = true in client.run the request should work

**Comment by Log4Jake** [comment]
where is client.run?
