### ISSUE TITLE
conn.get_var() returns a "NoneType" object

### ISSUE THREAD

**Issue by heyimocto** [TimMcCool/scratchattach#56]
^^^^

**Comment by mas6y6** [comment]
Hmmm.... You Need to talk to TimMcCool about this There Could be something wrong about your "conn" object in your py code

**Comment by heyimocto** [comment]
but idk

**Comment by TimMcCool** [comment]
This means the cloud variable you tried to get doesn't exist

**Comment by heyimocto** [comment]
Hm, my cloud variable does exist. I even double-checked if I was typing the name correctly, and if the project was saved.

**Comment by tt-thoma** [comment]
Wait a few seconds. There is sometimes latency between when a cloud var is set and the thread recording it

**Comment by scratching-claws** [comment]
I get this problem as well.  when the variable isn't set to 0 there is no problem but the moment it is changed to 0 or blank, it returns as NoneType.  This is only an issue for one of my projects

**Comment by jimjamgithub** [comment]
can you give some of your source code for when this is happening?

**Comment by TimMcCool** [comment]
If the error still happens, use scratch3.get_var("project_id", "variable") instead, this should work

**Comment by Flappy25** [comment]
> I get this problem as well. when the variable isn't set to 0 there is no problem but the moment it is changed to 0 or blank, it returns as NoneType. This is only an issue for one of my projects

it worked for me after I added the cloud icon in the var name
