### ISSUE TITLE
How to set a cloud variable with CloudEvents

### ISSUE THREAD

**Issue by tt-thoma** [TimMcCool/scratchattach#62]
I've been searching on the wiki and on Scratch for a while but I have no clue how to set a variable with the CloudEvents thing. When looking into _requests.py I see you just did it manually... How am I supposed to do it ?

**Comment by TimMcCool** [comment]
You can't set cloud variables with CloudEvents, use CloudRequests for that: https://github.com/TimMcCool/scratchattach/wiki/Cloud-Requests
