### ISSUE TITLE
Project Connect Error

### ISSUE THREAD

**Issue by TechHopGitHub** [TimMcCool/scratchattach#63]
I'm getting this error: `Traceback (most recent call last):
  File "d:\Python\Scratch Cloud Requests\main.py", line 6, in <module>
    conn = session.connect_cloud(813916919)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.connect_cloud() takes 1 positional argument but 2 were given`

And here's my code: `import scratchattach as scratch3

session_id = "**************************************************"
session = scratch3.Session(session_id, username="CodeSoft_Games") #replace with your session_id and username
conn = session.connect_cloud(813916919)

client = scratch3.CloudRequests(conn)

@client.request
def ping(): #called when client receives request
    print("Ping request received")
    return "pong" #sends back 'pong' to the Scratch project

@client.event
def on_ready():
    print("Request handler is running")
client.run() #make sure this is ALWAYS at the bottom of your Python file`

**Comment by jimjamgithub** [comment]
can you try and remove your session ID from the message first? Other people could get into your account.

**Comment by jimjamgithub** [comment]
The issue is you have to use quotes " "  around the project ID. change
`conn = scratch3.connect_cloud(813916919)`
 to 
`conn = scratch3.connect_cloud("813916919")` 
and that should work.

**Comment by TechHopGitHub** [comment]
Did not fix it.

**Comment by TechHopGitHub** [comment]
Nevermind, turns out installing Scratchattatch by using -U fixed it.
