### ISSUE TITLE
How to send a dictionary?

### ISSUE THREAD

**Issue by TechHopGitHub** [TimMcCool/scratchattach#64]
I need to send a .txt file, which was converted into a dictionary, which I need to send it all. What do I do? No, I cannot use commas because my text lines use commas.

**Comment by tt-thoma** [comment]
It's quite complicated, but you have to encrypt your dictionary object into numbers, which you will send to the project via setting a cloud variable (with max length 256) and you need to include something to decode the dictionary inside the scratch project

**Comment by TimMcCool** [comment]
You can send lists using cloud requests.
