### ISSUE TITLE
To many requests

### ISSUE THREAD

**Issue by AxeToOcelot** [TimMcCool/scratchattach#66]
i did

while True:
  Ping = Project.get_var("Ping")
  print(Ping)
  if Ping == 1:
    print("Pong")
    City_Requested = Project.get_var("City")
    Units = Project.get_var("Unit")
    Decode(City_Requested)
    GeoCode(Decoded)
    Decode(Units)
    Get_Temperature(Latitude,Longitude, Decoded)
    Project.set_var("Temperature", round(Temperature))
    Project.set_var("Ping", 0)
  
  time.sleep(10)

there is like 50 other lines of code but this is all that actualy interacts with the project
no errors but it is not working also when go scratch3.get_health() it says to many requests
here is replit link https://replit.com/@CodeKid11/ScratchAttach-Weather

**Comment by tt-thoma** [comment]
The error "too many requests" means that you're using the scratch API (like set or get variable) too munch. Try putting a sleep(0.1) in the while True loop, as scratch servers update variables at this frequency

**Comment by AxeToOcelot** [comment]
the time.sleep is in the while true loop

**Comment by AxeToOcelot** [comment]
check the replit link

**Comment by AxeToOcelot** [comment]
Wait it is getting cloud vars but not setting cloud vars

**Comment by tt-thoma** [comment]
> Wait it is getting cloud vars but not setting cloud vars

Because scratch blocked the reply IP address

**Comment by AxeToOcelot** [comment]
but it was working earlier
and what is fix

**Comment by TechHopGitHub** [comment]
> but it was working earlier and what is fix

Don't use replit, host on your local machine for testing, the use something like AWS.

**Comment by tt-thoma** [comment]
> Don't use replit, host on your local machine for testing, the use something like AWS.

AWS is a paid service, and I don't think you should use it when there is alternatives like PythonAnywhere that will work well even if it has limited usage rates and need to be renewed every month

**Comment by TimMcCool** [comment]
You can't use scratchattach on pythonanywhere because scratch blocked replit. I might implement a way to use scratchattach on replit in the future

**Comment by tt-thoma** [comment]
> You can't use scratchattach on pythonanywhere because scratch blocked replit. I might implement a way to use scratchattach on replit in the future

My bad I tought PythonAnywhere was apart from replit

**Comment by TechHopGitHub** [comment]
> You can't use scratchattach on pythonanywhere because scratch blocked replit. I might implement a way to use scratchattach on replit in the future

This could just be a proxy, and I could see something like that in the future.
