### ISSUE TITLE
Error Decoding

### ISSUE THREAD

**Issue by Log4Jake** [TimMcCool/scratchattach#67]
When I run this replit sometimes I get this error. It says Line 63 which is just `decoded = Encoding.decode(encoded)`
the project is [project](https://scratch.mit.edu/projects/780104691/) and the repl is [repl](https://replit.com/@jakt2021/Scratch-Coin)

The error is

`Exception in thread Thread-3 (_update):
Traceback (most recent call last):
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/Scratch-Coin/venv/lib/python3.10/site-packages/scratchattach/_cloud.py", line 232, in _update
    self._events["on_"+activity["verb"][:-4]](self.Event(user=activity["user"], var=activity["name"][2:], name=activity["name"][2:], value=activity["value"], timestamp=activity["timestamp"]))
  File "main.py", line 63, in on_set
    decoded = Encoding.decode(encoded)
  File "/home/runner/Scratch-Coin/venv/lib/python3.10/site-packages/scratchattach/_encoder.py", line 119, in decode
    letter = letters[int(f"{inp[i*2]}{inp[(i*2)+1]}")]
ValueError: invalid literal for int() with base 10: 'No'`

Edit: I check what the variable is set to before the error occurs and it is `None` which I assume is nonetype but the cloud variable is 0

**Comment by tt-thoma** [comment]
The scratch servers will never return anything to the replit servers because the replit IP is blocked, giving the "None". Also when a cloud var is set to nothing it will
return an empty string instead

**Comment by Log4Jake** [comment]
But I've never had a problem before and it still works occasionally. I am also using the session and not the login.

**Comment by TimMcCool** [comment]
You can also get the value of the cloud variable using event.value, this should never return None:
```py
@events.event
def on_set(event): #Called when a cloud var is set
    print({event.var})
    if {event.var} == {'REQUEST'}:
      print(accounts)
      backup = open('backup', 'wb')
      pickle.dump(accounts, backup)
      backup.close()
      encoded = event.value
```
