### ISSUE TITLE
Getting Cookies Are More Difficult

### ISSUE THREAD

**Issue by wolfieboy09** [TimMcCool/scratchattach#68]
So you can't get cookies the normal way now. It's a **lot** harder now.

The only way I know is to log in, then get the `session_id` attribute from the login

Why did Google have to do this :(

The new way thing
![image](https://user-images.githubusercontent.com/105564186/234697630-d9c6460e-cebd-49d1-a81d-131af3d5192e.png)

**Comment by lemystic** [comment]
You could also just use Firefox

**Comment by mas6y6pro** [comment]
I have found a solution
https://scratch.mit.edu/projects/843533060/

**Comment by TimMcCool** [comment]
Yeah, I just noticed that too. I don't know why Google did that :(
The old way still works in other browsers like Microsoft Edge. There's another way to get your session id that still works: https://github.com/TimMcCool/scratchattach/wiki/Get-your-session-id It's more complicated though
