### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by jimjamgithub** [TimMcCool/scratchattach#7]
so, while trying to log in to my account in scratchattach, it firstly returns with:
`Failed to login. Either the provided authentication data is wrong or your network is banned from Scratch`
The authentication data is correct, and i did login with the same account on the same network after that.
Then this long error message comes:
```
Traceback (most recent call last):
  File "/home/runner/mmo-crasher/venv/lib/python3.8/site-packages/scratchattach/_session.py", line 240, in login
    session_id = str(re.search('"(.*)"', request.headers["Set-Cookie"]).group())
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    session = scratch3.login("", "")
  File "/home/runner/mmo-crasher/venv/lib/python3.8/site-packages/scratchattach/_session.py", line 243, in login
    raise(_exceptions.LoginFailure)
scratchattach._exceptions.LoginFailure
```
also, the same code worked about an hour earlier
i'm using replit btw

_Edit: Removed login data - TimMcCool_

**Comment by TimMcCool** [comment]
Scratch banned some of replit's IP adresses, so logging in from replit will not always work. `scratchattach._exceptions.LoginFailure` is raised when Scratch blocks the login request.

**Comment by jimjamgithub** [comment]
oh ok, thats annoying
(also didn't realise i left login details in the error message, thanks for removing)

**Comment by catguy323** [comment]
how do you make it access the forked repl

**Comment by TimMcCool** [comment]
The info from this issue is no longer up to date. Scratch blocked replit from accessing all API endpoints (except for cloud variables) about two years ago.
