### ISSUE TITLE
No module named 'scratchattach'

### ISSUE THREAD

**Issue by MegaBaconator** [TimMcCool/scratchattach#74]
I have scratchattatch installed via the command prompt, and when I try to run it, it gives me this error:

Traceback (most recent call last):
  File "C:/Users/XXXXX/Documents/hack.py", line 5, in <module>
    import scratchattach as scratch3
ModuleNotFoundError: No module named 'scratchattach'

**Comment by jimjamgithub** [comment]
if you are using vscode, you will have to switch python interpreter. press ctrl+p and search "python interpreter" click on the "change python interpreter option, and try to click on the option that isn't highlighted. If that doesn't work, do the same thing again and click on the other one. if that works, then all issues with scratchattach and any other modules would of been fixed.

**Comment by craftingdead261** [comment]
i am having the same problem

**Comment by TodToucan** [comment]
Hi. Scratchattach is not installing. It keeps saying 'SyntaxError: multiple statements found while compiling a single statement'. What should I do?

**Comment by TimMcCool** [comment]
> Hi. Scratchattach is not installing. It keeps saying 'SyntaxError: multiple statements found while compiling a single statement'. What should I do?

Run the command in the command prompt / shell, not in the python console

**Comment by mas6y6** [comment]
Use "pip" command instead of "pip3"

```shell
pip install scratchattach
```

**OR**

Try checking your python interpreter

**Comment by TimMcCool** [comment]
closing topic due to inactivity
