### ISSUE TITLE
get_topic_list()

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#75]
def get_topic_list(category_name, *, page=0, include_deleted=False):
    category_name.replace(" ", "%20") # Should be 'category_name = category_name.replace(" ", "%20")'
    if include_deleted:
        filter = 0
    else:
        filter = 1
    try:
        data = requests.get(f"https://scratchdb.lefty.one/v3/forum/category/topics/{category_name}/{page}?detail=1&filter={filter}").json()
        return_data = []
        for topic in data:
            t = ForumTopic(id = topic["id"])
            t._update_from_dict(topic)
            return_data.append(t)
        return return_data
    except Exception:
        return None

**Comment by TimMcCool** [comment]
Will be fixed soon

**Comment by TimMcCool** [comment]
Will be fixed in v1.1.8
