### ISSUE TITLE
Profile Bot

### ISSUE THREAD

**Issue by Profrozer** [TimMcCool/scratchattach#79]
I'm having a new invention. I want to make a bot take can reply the messages on my profile. Like when I type "!" ("!hi") then another account will reply it. I just don't know how do I get the first messages and reply to it

**Comment by GitbyteMaster** [comment]
Hello! I'm not the one to be answering your question, but I'd just like to say that bots for Scratch can actually get you banned. Just letting you know.

**Comment by Profrozer** [comment]
lol, okay thanks!

**Comment by TheCommCraft** [comment]
You can close the topic by yourself

**Comment by TimMcCool** [comment]
To get your profile comments, use

```
import scratchattach as sa

session = sa.Session("botsessionid", username="botusername")
user = session.connect_user("yourusername")

#Get comments:
comments = user.comments()

#Reply to the first comment
user.reply_comment("content", parent_id=comments[0]["CommentID"])
