### ISSUE TITLE
What is parent id and commetee id?

### ISSUE THREAD

**Issue by Profrozer** [TimMcCool/scratchattach#80]
Hi! I just wanted to know when I use scratchattach to post a comment of reply. What does the "user.post_comment("comment content", parent_id="", commentee_id="")" parent id and commetee id mean?

**Comment by 1and1is3** [comment]
I think parent_id is for a reply.

**Comment by slavikroblox** [comment]
ParentID is project ID

**Comment by slavikroblox** [comment]
And commentee I think TimMcCool just accidentally pressed e 2 times. The correct word is comment ID, it specifies comment ID if you are replying.

**Comment by TimMcCool** [comment]
if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user that will get a notification for your comment and will be mentioned in your comment

**Comment by slavikroblox** [comment]
> if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user will get a notification for your comment and will be mentioned in your comment

Sorry but commentee is not even a word

**Comment by TheCommCraft** [comment]
> > if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user will get a notification for your comment and will be mentioned in your comment
> 
> Sorry but commentee is not even a word

Yes it is. A commenter is somebody who comments and a commentee is the person they are commenting on.

**Comment by TimMcCool** [comment]
> > if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user will get a notification for your comment and will be mentioned in your comment
> 
> Sorry but commentee is not even a word

I did not come up with that word myself, it's from the Scratch API

**Comment by slavikroblox** [comment]
> > > if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user will get a notification for your comment and will be mentioned in your comment
> > 
> > 
> > Sorry but commentee is not even a word
> 
> I did not come up with that word myself, it's from the Scratch API

Ohh sorry then

**Comment by nashjames21** [comment]
> > if you want to reply to a comment, set parent_id to the id of the comment you want to reply to. if you set commentee_id to a user id, the user will get a notification for your comment and will be mentioned in your comment
> 
> Sorry but commentee is not even a word

Sorry but it IS a word

**Comment by FAReTek1** [comment]
It's not on the oxford dictionary. However that is not definitive.
