### ISSUE TITLE
It appears that your comments proxy is broken

### ISSUE THREAD

**Issue by PPPDUD** [TimMcCool/scratchattach#81]
Whenever I run import scratchattach as scratch3
user = scratch3.get_user("pppdud")
user.comments(limit=20, page=1) , I get the following error in line three: **Traceback (most recent call last):
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#129>", line 1, in <module>
    user.comments(limit=20, page=1)
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\site-packages\scratchattach\_user.py", line 483, in comments
    ).json()
  File "C:\Users\birdspeed100\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html>
<html lang="en">
  <head>
    <title>Run this Repl to see the results here.</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans">
    <style>
      body {
        margin: 0;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        background: #1c2333;
        font-family: "IBM Plex Sans", "sans";
        color: #f5f9fc;
      }

      .title-box {
        font-size: 12px;
        inline-size: max-content;
      }

      .err-box {
        padding: 1em;
        max-width: 30em;
        width: 100vw;
      }

      .message {
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      @media (max-width: 500px) {
        .message {
          flex-direction: column;
          align-items: center;
        }
      }

      .eval-bot {
        margin: 2em;
      }

      .console {
        background-color: #0e1628;
        color: #fff;
        font-family: "IBM Plex Sans", "sans";
        padding: 1em;
        margin: 1em;
      }

      .footer {
        margin: 1em;
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .link-icon {
        margin-right: 20px;
        margin-top: 4px;
      }

      a {
        color: #c2c8cc;
      }
    </style>

    <script>
      var reload_timeout = setTimeout(function () {
        window.location.reload();
      }, 60000);
    </script>
  </head>

  <body>
    <div class="err-box">
      <div class="message">
        <div class="eval-bot">
          <svg
            width="290"
            height="147"
            viewBox="0 0 290 147"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M286.619 23.7207C289.534 27.4209 290.848 32.8497 287.611 40.7404C278.97 61.797 266.814 96.0691 266.814 96.0691C266.814 96.0691 263.84 110.374 247.366 110.374H81.9192L69.2234 94.1967L269.605 4.86339L273.294 6.84472L286.619 23.7207Z"
              fill="#006D21"
            />
            <path
              d="M69.2235 94.1967H234.671C251.144 94.1967 254.119 79.8915 254.119 79.8915C254.119 79.8915 266.274 45.6144 274.939 24.5628C283.605 3.51112 259.815 0.00416558 259.815 0.00416558H90.7234C90.7234 0.00416558 78.9745 -0.669489 71.2757 15.1168C63.5769 30.903 55.0652 58.8398 55.0652 58.8398L69.2235 94.1967Z"
              fill="#77EA94"
            />
            <path
              d="M143.619 64.4024L163.245 20.5902L194.308 48.5716L143.619 64.4024Z"
              fill="#006D21"
            />
            <path
              d="M117.935 55.9471L130.541 50.9095L117.751 94.4543V110.285H91.824L117.935 55.9471Z"
              fill="#1D2332"
            />
            <path
              d="M130.105 13.9131L129.406 36.1585L90.5153 119.825L91.2093 97.5798L130.105 13.9131Z"
              fill="#283DC9"
            />
            <path
              d="M29.6288 88.4013L45.4974 75.1214L18.3954 61.8118L130.105 13.9131L91.2093 97.5798L67.4734 85.9197L26.3768 124.244L1.69403 111.786L29.6288 88.4013Z"
              fill="#5162F6"
            />
            <path
              d="M91.2093 97.5798L90.5153 119.825L66.7794 108.165L67.4734 85.9197L91.2093 97.5798Z"
              fill="#162DA3"
            />
            <path
              d="M67.4734 85.9197L66.7794 108.165L25.6828 146.489L26.3768 124.244L67.4734 85.9197Z"
              fill="#283DC9"
            />
            <path
              d="M26.3768 124.244L25.6828 146.489L1 134.031L1.69403 111.786L26.3768 124.244Z"
              fill="#162DA3"
            />
            <path
              d="M45.4974 75.1214L29.6288 88.4013L20.3486 83.1211L18.3954 61.8118L45.4974 75.1214Z"
              fill="#162DA3"
            />
            <path
              d="M130.105 13.9131L18.3954 61.8118L45.4974 75.1214L29.6288 88.4013L1.69403 111.786L26.3768 124.244L67.4734 85.9197L91.2093 97.5798L130.105 13.9131Z"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
            <path
              d="M130.105 13.9131L129.406 36.1585L90.5153 119.825L66.7794 108.165L25.6828 146.489L1 134.031L1.69403 111.786"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
            <path
              d="M18.3954 61.8118L20.3486 83.1211L29.6288 88.4013L29.6586 88.4211"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
            <path
              d="M66.7794 108.165L67.4734 85.9197"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
            <path
              d="M91.2093 97.5798L90.5153 119.825"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
            <path
              d="M26.3768 124.244L25.6828 146.489"
              stroke="#1D2332"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </div>
        <div class="title-box">
          <h1>Run this Repl to see the results here.</h1>
        </div>
      </div>
      <div class="footer">
        <div class="link-icon">
          <svg
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M6.66668 8.66666C6.95298 9.04942 7.31825 9.36612 7.73771 9.59529C8.15717 9.82446 8.62102 9.96074 9.09778 9.99489C9.57454 10.029 10.0531 9.96024 10.5009 9.79319C10.9487 9.62613 11.3554 9.36471 11.6933 9.02666L13.6933 7.02666C14.3005 6.39799 14.6365 5.55598 14.6289 4.68199C14.6213 3.808 14.2708 2.97196 13.6527 2.35394C13.0347 1.73591 12.1987 1.38535 11.3247 1.37775C10.4507 1.37016 9.60869 1.70614 8.98001 2.31333L7.83334 3.45333M9.33334 7.33333C9.04704 6.95058 8.68177 6.63388 8.26231 6.4047C7.84285 6.17553 7.37901 6.03925 6.90224 6.00511C6.42548 5.97096 5.94695 6.03975 5.49911 6.20681C5.05128 6.37387 4.6446 6.63528 4.30668 6.97333L2.30668 8.97333C1.69948 9.602 1.3635 10.444 1.3711 11.318C1.37869 12.192 1.72926 13.028 2.34728 13.6461C2.96531 14.2641 3.80135 14.6147 4.67534 14.6222C5.54933 14.6298 6.39134 14.2939 7.02001 13.6867L8.16001 12.5467"
              stroke="#C2C8CC"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </div>
        <div class="repl-links">
          <a href="https://replit.com">Go to Replit</a>
        </div>
        <div></div>
      </div>
    </div>
  </body>
</html>
: 0
**

**Comment by TimMcCool** [comment]
update scratchattach to the latest version to fix the issue

**Comment by PPPDUD** [comment]
Okay! Thanks!
