### ISSUE TITLE
Comments not getting loaded

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#83]
When you use scratchattach._project.Project.comments it doesn't load any comments if there are less than 40 root comments

**Comment by TimMcCool** [comment]
i will look into it when i am at home

**Comment by TheCommCraft** [comment]
So..?

Tim ***@***.***> schrieb am Mo., 5. Juni 2023, 21:03:

**Comment by TimMcCool** [comment]
Will be fixed in v1.1.8
