### ISSUE TITLE
it wont let me login

### ISSUE THREAD

**Issue by zztwin01** [TimMcCool/scratchattach#9]
when i put the thing it says 'session' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TimMcCool** [comment]
What thing did you put to log in? Also, where did you run your Python code? To me it looks like you ran it in the command prompt without executing python

**Comment by zztwin01** [comment]
where am i supposed to run python code

**Comment by zztwin01** [comment]
and what does that even mean

**Comment by zztwin01** [comment]
im confused on how to do this

**Comment by zztwin01** [comment]
Nothing works

**Comment by zztwin01** [comment]
i downloaded python

**Comment by zztwin01** [comment]
i put in pip install scratchattach into command prompt

**Comment by zztwin01** [comment]
then i type in the login code and replace user with my user and password with my password

**Comment by zztwin01** [comment]
then nothing happens except errors

**Comment by zztwin01** [comment]
its basicly like 'blah bah blah' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zztwin01** [comment]
basically*

**Comment by zztwin01** [comment]
idk what im doing wrong

**Comment by zztwin01** [comment]
> What thing did you put to log in? Also, where did you run your Python code? To me it looks like you ran it in the command prompt without executing python

also the thing i put is import scratchattach as scratch3

session = scratch3.login("username", "password")

**Comment by zztwin01** [comment]
> What thing did you put to log in? Also, where did you run your Python code? To me it looks like you ran it in the command prompt without executing python
can you make a comment where you tell me what I need to do?

**Comment by zztwin01** [comment]
like a step by step guide of how to set it up that i can understand

**Comment by jimjamgithub** [comment]
basically, the reason you need to install python is to write code in it, which is how scratchattach, which is a module, (moudles are like addons in python)

**Comment by jimjamgithub** [comment]
> then i type in the login code and replace user with my user and password with my password

your supposed to do that in python

**Comment by jimjamgithub** [comment]
step by step thing:
1.install python(you did this)
2. do 'pip install scratchattach' in the command prompt (you also did this)
3. open IDLE(if you are using windows, you should be able to access this by searching in the start menu for "IDLE")
4. once idle has opened, press file and then new file
5. a simple text editor shows up. this is where the code goes.
6. put in the following to log into scratch(remember to use your login details)
```
import scratchattach as scratch3

session = scratch3.login("username", "password")

```
7. now, to check if it works, click on run, and the click run module(you will have to save it). if nothing but another >>> prompt shows up, it worked.

**Comment by jimjamgithub** [comment]
> step by step thing: 1.install python(you did this) 2. do 'pip install scratchattach' in the command prompt (you also did this) 3. open IDLE(if you are using windows, you should be able to access this by searching in the start menu for "IDLE") 4. once idle has opened, press file and then new file 5. a simple text editor shows up. this is where the code goes. 6. put in the following to log into scratch(remember to use your login details)
> 
> ```
> import scratchattach as scratch3
> 
> session = scratch3.login("username", "password")
> ```
> 
> 7. now, to check if it works, click on run, and the click run module(you will have to save it). if nothing but another >>> prompt shows up, it worked.

hope  this was useful!

**Comment by zztwin01** [comment]
i think its almost working but an error said Traceback (most recent call last):
  File "C:/Users/no/AppData/Local/Programs/Python/Python310/scratchattach.py", line 1, in <module>
    import scratchattach as scratch3
  File "C:\Users/david/AppData/Local/Programs/Python/Python310\scratchattach.py", line 3, in <module>
    session = scratch3.login("zztwin1", "no")
AttributeError: partially initialized module 'scratchattach' has no attribute 'login' (most likely due to a circular import)

**Comment by jimjamgithub** [comment]
ahhh

**Comment by jimjamgithub** [comment]
you cant name the file scratchattach, otherwise instead of using the actual module for the import, it will import your file. so just name it something like scratchattach_test.py

**Comment by jimjamgithub** [comment]
circular imports are when a "import imports itself"

**Comment by zztwin01** [comment]
IT WORKS

**Comment by zztwin01** [comment]
THANKS

**Comment by zztwin01** [comment]
but how do i run the code for setting cloud variables and stuff

**Comment by zztwin01** [comment]
am i supposed to do it like this? 
![image](https://user-images.githubusercontent.com/105742514/169342369-e842ebbf-44ff-45fd-98a5-c7f5be14edfa.png)

**Comment by tympanicblock61** [comment]
> am i supposed to do it like this? ![image](https://user-images.githubusercontent.com/105742514/169342369-e842ebbf-44ff-45fd-98a5-c7f5be14edfa.png)

yes
