### ISSUE TITLE
Documentation for WsCloudEvents

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#90]
Maybe you could add a documentation for the scratchattach._cloud.WsCloudEvents class

**Comment by TimMcCool** [comment]
Okay, will be added soon. scratchattach._cloud.WsCloudEvents are cloud events that use a scratchattach._cloud.CloudConnection class to receive cloud variable updates

**Comment by TheCommCraft** [comment]
I know, but not everyone does
