### ISSUE TITLE
ScratchAttach on Ubuntu - is it possible?

### ISSUE THREAD

**Issue by xendyex** [TimMcCool/scratchattach#95]
I'll try to install with pip or the sudo apt install python3-scratchattach. Just says, with pip, basically, use Sudo. But, sudo tells me SA doesn't exist... any help?

**Comment by EntentaPL** [comment]
idk, 
`sudo pip3 install scratchattach`

**Comment by mas6y6** [comment]
I use a raspberry pi to start my scratchattach server

(Linux)

```Shell
sudo pip3 install scratchattach
```
**OR**
```Shell
pip install scratchattach
```

**Comment by EntentaPL** [comment]
this same
