### ISSUE TITLE
Put warning for this

### ISSUE THREAD

**Issue by Ellirio** [TimMcCool/scratchattach#97]
hi tim! theres this issue with Scratchattach well not really an issue but a annoying problem for the last month i have been thinking my sessionID is messed up when i got a new one. But the problem was that when you make the session variable and set username to your username it has to be extact capitals like if i put loidesmio it wont work but if i put LoIdesMio lol and for the last month i have been wondering why it hasn't been working mainly my fault but like you should probably put like a warning or something.

**Comment by TimMcCool** [comment]
Okay, I'll add a warning about it in the docs

**Comment by PhiIHub** [comment]
> hi tim! theres this issue with Scratchattach well not really an issue but a annoying problem for the last month i have been thinking my sessionID is messed up when i got a new one. But the problem was that when you make the session variable and set username to your username it has to be extact capitals like if i put loidesmio it wont work but if i put LoIdesMio lol and for the last month i have been wondering why it hasn't been working mainly my fault but like you should probably put like a warning or something.

Lol that is so obvious
